<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DefineConstants>$(DefineConstants);TUNIT</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\ProtoTest.TUnit\ProtoTest.TUnit.csproj" />
  </ItemGroup>
</Project>
