<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProtoTest.AdapterContract\ProtoTest.AdapterContract.csproj" />
    <ProjectReference Include="..\..\src\ProtoTest.TUnit\ProtoTest.TUnit.csproj" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ProtoTest.TestSupport\ProtoTest.TestSupport.csproj" />
  </ItemGroup>
</Project>
