namespace ProtoTest.Core;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Defines the builder contract for constructing and configuring a <see cref="ProtoHost"/>.
/// </summary>
public interface IProtoHostBuilder
{
    /// <summary>
    /// Registers dependencies with the internal service collection.
    /// </summary>
    /// <returns>The current <see cref="IProtoHostBuilder"/> instance.</returns>
    IProtoHostBuilder ConfigureServices(Action<IServiceCollection> configure);

    /// <summary>
    /// Registers a global execution lifecycle hook.
    /// </summary>
    /// <returns>The current <see cref="IProtoHostBuilder"/> instance.</returns>
    IProtoHostBuilder AddTestHook<THook>() where THook : class, IProtoTestHook;

    /// <summary>
    /// Registers a suite-level lifecycle hook.
    /// </summary>
    IProtoHostBuilder AddRunHook<TRunHook>() where TRunHook : class, IProtoRunHook;

    /// <summary>
    /// Configures the application configuration (appsettings.json, environment variables, etc.).
    /// </summary>
    /// <returns>The current <see cref="IProtoHostBuilder"/> instance.</returns>
    IProtoHostBuilder ConfigureAppConfiguration(Action<IConfigurationBuilder> configure);

    /// <summary>Configures numeric test execution IDs generated by the host.</summary>
    IProtoHostBuilder ConfigureTestIds(Action<ProtoTestIdOptions> configure);

    /// <summary>Configures the automatic execution trace written by ProtoTest.Core.</summary>
    IProtoHostBuilder ConfigureTracing(Action<ProtoTraceOptions> configure);

    /// <summary>
    /// Registers a Run gate evaluated once the suite finishes. Gates see everything the run's
    /// collectors produced; a failed gate fails the run after the reports are written.
    /// </summary>
    IProtoHostBuilder AddRunGate<TGate>() where TGate : class, IProtoRunGate;

    /// <summary>Registers a Run gate defined by a delegate.</summary>
    IProtoHostBuilder AddRunGate(string name, Func<ProtoRunGateContext, ProtoRunGateResult> evaluate);

    /// <summary>
    /// Registers a run-scoped resource: infrastructure the whole suite owns, such as a database
    /// container, released when the host is disposed after the run has stopped.
    /// </summary>
    IProtoHostBuilder AddResource(IProtoResource resource);

    /// <summary>
    /// Builds and initializes the configured <see cref="ProtoHost"/> instance.
    /// </summary>
    /// <returns>A fully configured <see cref="ProtoHost"/>.</returns>
    ProtoHost Build();
}
