<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <DefineConstants>$(DefineConstants);MSTEST</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\ProtoTest.MSTest\ProtoTest.MSTest.csproj" />
  </ItemGroup>
</Project>
