namespace ProtoTest.Core;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using ProtoTest.Core.Internal;
using System.Reflection;

/// <summary>
/// Provides the public per-test façade for metadata, services, state, clients, attachments, and observations.
/// </summary>
public sealed class ProtoExecutionContext : IAsyncDisposable
{
    private readonly IServiceScope _scope;
    private readonly ProtoAttachmentCollection _attachments;
    private readonly ProtoContextStateStore _state = new();
    private readonly ProtoClientRegistry _clients = new();
    private readonly ProtoResourceRegistry _resources = new();
    private readonly ProtoObservationDispatcher _observations;
    private int _disposeStarted;
    private int _findingSequence;

    public ProtoExecutionContext(string testName, IServiceScope scope, string testId, MethodInfo testMethod)
        : this(testName, scope, ProtoTestId.Parse(testId), testMethod)
    {
    }

    public ProtoExecutionContext(string testName, IServiceScope scope, ProtoTestId id, MethodInfo testMethod)
        : this(testName, scope, id, testMethod, new ProtoTestTraceRecorder(id.Value, testName, testMethod))
    {
    }

    internal ProtoExecutionContext(
        string testName,
        IServiceScope scope,
        ProtoTestId id,
        MethodInfo testMethod,
        ProtoTestTraceRecorder trace)
    {
        TestName = testName ?? throw new ArgumentNullException(nameof(testName));
        _scope = scope ?? throw new ArgumentNullException(nameof(scope));
        Id = id;
        TestMethod = testMethod ?? throw new ArgumentNullException(nameof(testMethod));
        _attachments = new ProtoAttachmentCollection(TestId);
        _observations = new ProtoObservationDispatcher(_scope.ServiceProvider);
        Trace = trace;
    }

    public string TestName { get; }
    public MethodInfo TestMethod { get; }

    /// <summary>
    /// Numeric execution ID generated by the owning host. The string form preserves leading zeroes.
    /// </summary>
    public ProtoTestId Id { get; }
    public string TestId => Id.Value;
    public long TestNumber => Id.Number;

    /// <summary>Records automatic execution diagnostics for ProtoTest integrations.</summary>
    public IProtoTraceWriter Trace { get; }

    /// <summary>Retrieves the global configuration registered in the ProtoHost.</summary>
    public IConfiguration Configuration => Service<IConfiguration>();

    public IServiceProvider Services => _scope.ServiceProvider;
    public T Service<T>() where T : notnull => Services.GetRequiredService<T>();
    public T? TryService<T>() => Services.GetService<T>();

    /// <summary>Gets a snapshot of the artifacts registered for this test.</summary>
    public IReadOnlyList<ProtoTestAttachment> Attachments => _attachments.Snapshot();

    public ProtoTestAttachment AddAttachment(
        string name,
        string content,
        string mediaType = "text/plain",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromText(name, content, mediaType, description));

    public ProtoTestAttachment AddAttachment(
        string name,
        ReadOnlyMemory<byte> content,
        string mediaType = "application/octet-stream",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromBytes(name, content, mediaType, description));

    public ProtoTestAttachment AddAttachmentFile(
        string filePath,
        string? name = null,
        string mediaType = "application/octet-stream",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromFile(filePath, name, mediaType, description));

    public ProtoTestAttachment AddAttachment(ProtoTestAttachment attachment)
    {
        var registered = _attachments.Add(attachment);
        Trace.WriteEvent(
            "attachment.register",
            $"Attachment · {registered.Name}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["attachment.name"] = registered.Name,
                ["attachment.media_type"] = registered.MediaType,
                ["attachment.description"] = registered.Description,
                ["attachment.source"] = registered.IsFile ? "file" : "memory"
            });
        return registered;
    }

    /// <summary>Registers or replaces contextual state for this test.</summary>
    public void SetContext<T>(T context) where T : class, IProtoContext
    {
        _state.Set(context);
        Trace.WriteEvent(
            "context.set",
            $"Context · {typeof(T).Name}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["context.type"] = typeof(T).FullName,
                ["context.value"] = ProtoTraceValueFormatter.Serialize(context)
            });
    }

    /// <summary>Retrieves contextual state when it is present.</summary>
    public T? TryResolve<T>() where T : class, IProtoContext
    {
        var context = _state.TryGet<T>();
        Trace.WriteEvent(
            "context.try_resolve",
            $"Try context · {typeof(T).Name}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["context.type"] = typeof(T).FullName,
                ["context.found"] = (context is not null).ToString().ToLowerInvariant()
            });
        return context;
    }

    /// <summary>Retrieves required contextual state.</summary>
    public T Resolve<T>() where T : class, IProtoContext
    {
        try
        {
            var context = _state.Get<T>();
            Trace.WriteEvent(
                "context.resolve",
                $"Resolve context · {typeof(T).Name}",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Succeeded,
                attributes: new Dictionary<string, string?>
                {
                    ["context.type"] = typeof(T).FullName
                });
            return context;
        }
        catch (Exception exception)
        {
            Trace.WriteEvent(
                "context.resolve",
                $"Resolve context · {typeof(T).Name}",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Failed,
                attributes: new Dictionary<string, string?> { ["context.type"] = typeof(T).FullName },
                exception: exception);
            throw;
        }
    }

    /// <summary>
    /// Registers a named client for this test. The client is owned by the test and released in reverse
    /// registration order when the test completes; pass <paramref name="disposeWithContext"/> as
    /// <see langword="false"/> for shared clients whose lifetime is managed elsewhere.
    /// </summary>
    public void RegisterClient<TClient>(TClient client, string name = "Default", bool disposeWithContext = true)
        where TClient : class
    {
        ArgumentNullException.ThrowIfNull(client);
        _clients.Register(client, name);
        RegisterOwned(new ProtoResource(
            $"client:{typeof(TClient).FullName}:{name}",
            "client",
            $"{(disposeWithContext ? "Client" : "Shared client")} {typeof(TClient).Name} '{name}'",
            context => ReleaseClientAsync(client, disposeWithContext)));
        Trace.WriteEvent(
            "client.register",
            $"Register · {name} ({typeof(TClient).Name})",
            "ProtoTest.Core",
            phase: ProtoTracePhase.Setup,
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["client.name"] = name,
                ["client.type"] = typeof(TClient).FullName,
                ["instance.type"] = client.GetType().FullName,
                ["client.owned"] = disposeWithContext ? "true" : "false"
            });
    }

    /// <summary>Retrieves a required named client.</summary>
    public TClient Client<TClient>(string name = "Default") where TClient : class
    {
        var attributes = new Dictionary<string, string?>
        {
            ["client.name"] = name,
            ["client.type"] = typeof(TClient).FullName
        };
        try
        {
            var client = _clients.Get<TClient>(name);
            Trace.WriteEvent(
                "client.resolve",
                $"Resolve · {name} ({typeof(TClient).Name})",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Succeeded,
                attributes: attributes);
            return client;
        }
        catch (Exception exception)
        {
            Trace.WriteEvent(
                "client.resolve",
                $"Resolve · {name} ({typeof(TClient).Name})",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Failed,
                attributes: attributes,
                exception: exception);
            throw;
        }
    }

    /// <summary>Retrieves a named client when it is present.</summary>
    public TClient? TryClient<TClient>(string name = "Default") where TClient : class
    {
        var client = _clients.TryGet<TClient>(name);
        Trace.WriteEvent(
            "client.try_resolve",
            $"Try resolve · {name} ({typeof(TClient).Name})",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["client.name"] = name,
                ["client.type"] = typeof(TClient).FullName,
                ["client.found"] = (client is not null).ToString().ToLowerInvariant()
            });
        return client;
    }

    /// <summary>Gets a snapshot of the resources owned by this test, in registration order.</summary>
    public IReadOnlyList<ProtoResourceSnapshot> Resources => _resources.Snapshot();

    /// <summary>
    /// Registers a resource owned by this test. Owned resources are released in reverse registration
    /// order during teardown, after hooks and attributes and before clients are disposed.
    /// </summary>
    public void RegisterResource(IProtoResource resource)
    {
        ArgumentNullException.ThrowIfNull(resource);
        RegisterOwned(resource);
        Trace.WriteEvent(
            "resource.register",
            $"Register · {resource.Id}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["resource.id"] = resource.Id,
                ["resource.kind"] = resource.Kind,
                ["resource.description"] = resource.Description
            });
    }

    /// <summary>Registers a resource and returns it, so ownership can be expressed inline.</summary>
    public T RegisterResource<T>(T resource) where T : class, IProtoResource
    {
        RegisterResource((IProtoResource)resource);
        return resource;
    }

    /// <summary>Registers a resource described by a release callback.</summary>
    public void RegisterResource(
        string id,
        string kind,
        string description,
        Func<ProtoResourceReleaseContext, ValueTask> release)
        => RegisterResource(new ProtoResource(id, kind, description, release));

    /// <summary>
    /// Releases one owned resource before teardown. Returns <see langword="false"/> when the resource
    /// is unknown or was already released.
    /// </summary>
    public ValueTask<bool> ReleaseResourceAsync(string id)
        => _resources.ReleaseAsync(id, this, Trace, ProtoTracePhase.Execution);

    /// <summary>
    /// Records a finding: something worth reporting that is deliberately not a test failure. Findings
    /// reach the run's reports and run gates, and are traced so they appear in ProtoTrace.
    /// </summary>
    public ProtoReportItem AddFinding(
        string message,
        ProtoReportStatus status = ProtoReportStatus.Warning,
        string? identifier = null,
        string? category = null,
        string? targetName = null,
        IReadOnlyList<string>? tags = null,
        IReadOnlyDictionary<string, object>? metadata = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(message);
        var sequence = Interlocked.Increment(ref _findingSequence);
        var item = new ProtoReportItem(
            TargetName: targetName ?? "Test findings",
            Category: category ?? "Finding",
            Identifier: identifier ?? $"finding-{sequence:D3}",
            Kind: ProtoReportItemKind.Finding,
            Status: status,
            Message: message,
            Tags: tags,
            Metadata: WithTestIdentity(metadata),
            DisplayGroup: TestName);
        TryService<ProtoFindingStore>()?.Add(item);
        Trace.WriteEvent(
            "finding.record",
            $"Finding · {item.Identifier}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["finding.status"] = status.ToString(),
                ["finding.target"] = item.TargetName,
                ["finding.category"] = item.Category,
                ["finding.message"] = message,
                ["finding.tags"] = tags is null ? null : string.Join(", ", tags)
            });
        return item;
    }

    private IReadOnlyDictionary<string, object> WithTestIdentity(IReadOnlyDictionary<string, object>? metadata)
    {
        var merged = metadata is null
            ? new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase)
            : new Dictionary<string, object>(metadata, StringComparer.OrdinalIgnoreCase);
        merged["test.id"] = TestId;
        merged["test.name"] = TestName;
        return merged;
    }

    /// <summary>Gets a snapshot of observations recorded for this test.</summary>
    public IReadOnlyCollection<ProtoObservation> RecordedObservations => _observations.Snapshot();

    /// <summary>Stores and dispatches an observation to every collector that accepts it.</summary>
    public void RecordObservation(ProtoObservation observation)
    {
        _observations.Record(observation);
        Trace.WriteEvent(
            "observation.record",
            $"Observation · {observation.Kind}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["observation.target"] = observation.TargetName,
                ["observation.kind"] = observation.Kind,
                ["observation.identifier"] = observation.Identifier,
                ["observation.data"] = ProtoTraceValueFormatter.Serialize(observation.Data),
                ["observation.metadata"] = ProtoTraceValueFormatter.Serialize(observation.Metadata)
            });
    }

    /// <summary>Convenience overload for recording an observation.</summary>
    public void RecordObservation(
        string targetName,
        string kind,
        string identifier,
        object? data = null,
        IReadOnlyDictionary<string, object>? metadata = null)
        => RecordObservation(new ProtoObservation(targetName, kind, identifier, data, metadata));

    /// <summary>
    /// Releases owned resources, disposes owned clients and the service scope. Disposal is idempotent
    /// and attempts every resource.
    /// </summary>
    public ValueTask DisposeAsync() => DisposeAsync(ProtoTracePhase.Teardown);

    /// <summary>
    /// Releases owned resources, disposes owned clients and the service scope. Disposal is idempotent
    /// and attempts every resource.
    /// </summary>
    internal async ValueTask DisposeAsync(ProtoTracePhase phase)
    {
        if (Interlocked.Exchange(ref _disposeStarted, 1) != 0)
        {
            return;
        }

        _clients.Seal();
        var exceptions = (await _resources.ReleaseAllAsync(this, Trace, phase)).ToList();
        try
        {
            if (_scope is IAsyncDisposable asyncDisposable)
            {
                await asyncDisposable.DisposeAsync();
            }
            else
            {
                _scope.Dispose();
            }
        }
        catch (Exception exception)
        {
            exceptions.Add(exception);
        }

        if (exceptions.Count > 0)
        {
            throw new AggregateException("One or more execution context resources failed to dispose.", exceptions);
        }
    }

    private void RegisterOwned(IProtoResource resource) => _resources.Register(resource);

    private static async ValueTask ReleaseClientAsync(object client, bool dispose)
    {
        if (!dispose)
        {
            return;
        }

        if (client is IAsyncDisposable asyncDisposable)
        {
            await asyncDisposable.DisposeAsync();
        }
        else if (client is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
}
