namespace ProtoTest.Core;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.Reflection;

/// <summary>
/// Owns the ProtoTest service provider and exposes the public run and test lifecycle API.
/// Lifecycle execution is delegated to focused internal components.
/// </summary>
public sealed class ProtoHost : IAsyncDisposable
{
    private readonly IServiceProvider _rootServiceProvider;
    private readonly ProtoRunLifecycle _runLifecycle;
    private readonly ProtoTestLifecycle _testLifecycle;

    public ProtoHost(IServiceProvider rootServiceProvider)
    {
        _rootServiceProvider = rootServiceProvider ?? throw new ArgumentNullException(nameof(rootServiceProvider));

        var testHooks = _rootServiceProvider.GetServices<IProtoTestHook>().ToArray();
        var runHooks = _rootServiceProvider.GetServices<IProtoRunHook>().ToArray();
        var testIdGenerator = _rootServiceProvider.GetService<IProtoTestIdGenerator>()
            ?? new NumericProtoTestIdGenerator();

        _runLifecycle = new ProtoRunLifecycle(runHooks);
        _testLifecycle = new ProtoTestLifecycle(this, _rootServiceProvider, testHooks, testIdGenerator);
        ProtoHostRegistry.Register(this);
    }

    /// <summary>
    /// Gets the current test execution context for this asynchronous control flow.
    /// </summary>
    public static ProtoExecutionContext CurrentContext => ProtoTestLifecycle.CurrentContext;

    /// <summary>
    /// Gets the host owning the current test, or the sole active host outside a test.
    /// </summary>
    public static ProtoHost CurrentHost => ProtoHostRegistry.GetCurrent(ProtoTestLifecycle.CurrentHost);

    public IConfiguration Configuration => _rootServiceProvider.GetRequiredService<IConfiguration>();

    /// <summary>
    /// Executes all suite-level BeforeRun hooks in ascending order.
    /// </summary>
    public Task StartAsync(CancellationToken cancellationToken = default)
        => _runLifecycle.StartAsync(cancellationToken);

    /// <summary>
    /// Executes all suite-level AfterRun hooks in descending order.
    /// </summary>
    public Task StopAsync(CancellationToken cancellationToken = default)
        => _runLifecycle.StopAsync(cancellationToken);

    /// <summary>
    /// Starts a test lifecycle with an explicit numeric ID.
    /// </summary>
    public Task<ProtoExecutionContext> StartTestAsync(
        string testName,
        string testId,
        MethodInfo testMethod,
        IEnumerable<ProtoAttribute>? attributes = null)
    {
        _runLifecycle.EnsureTestCanStart();
        return _testLifecycle.StartAsync(testName, ProtoTestId.Parse(testId), testMethod, attributes);
    }

    /// <summary>
    /// Starts a test lifecycle with an ID generated by this host.
    /// </summary>
    public Task<ProtoExecutionContext> StartTestAsync(
        string testName,
        MethodInfo testMethod,
        IEnumerable<ProtoAttribute>? attributes = null)
    {
        _runLifecycle.EnsureTestCanStart();
        return _testLifecycle.StartAsync(testName, testMethod, attributes);
    }

    /// <summary>
    /// Completes the active test using the exact lifecycle components that completed setup.
    /// </summary>
    public Task CompleteTestAsync() => _testLifecycle.CompleteAsync();

    public async ValueTask DisposeAsync()
    {
        if (!_runLifecycle.TryMarkDisposed())
        {
            return;
        }

        try
        {
            if (_rootServiceProvider is IAsyncDisposable asyncDisposable)
            {
                await asyncDisposable.DisposeAsync();
            }
            else if (_rootServiceProvider is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }
        finally
        {
            ProtoHostRegistry.Unregister(this);
        }
    }
}
