namespace ProtoTest.Core;

using System.Reflection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using ProtoTest.Core.Internal;

/// <summary>
/// Provides the public per-test façade for metadata, services, state, clients, attachments, and observations.
/// </summary>
public sealed class ProtoExecutionContext : IAsyncDisposable
{
    private readonly IServiceScope _scope;
    private readonly ProtoAttachmentCollection _attachments;
    private readonly ProtoContextStateStore _state = new();
    private readonly ProtoClientRegistry _clients = new();
    private readonly ProtoResourceRegistry _resources = new();
    private readonly HashSet<string> _reportedResources = new(StringComparer.Ordinal);
    private readonly ProtoObservationDispatcher _observations;
    private readonly ProtoFindingStore? _findings;
    private readonly ProtoClockRegistry? _clockRegistry;
    private int _disposeStarted;
    private int _findingSequence;
    private int _clientReplacementSequence;

    public ProtoExecutionContext(string testName, IServiceScope scope, string testId, MethodInfo testMethod)
        : this(testName, scope, ProtoTestId.Parse(testId), testMethod)
    {
    }

    public ProtoExecutionContext(string testName, IServiceScope scope, ProtoTestId id, MethodInfo testMethod)
        : this(testName, scope, id, testMethod, new ProtoTestTraceRecorder(id.Value, testName, testMethod))
    {
    }

    internal ProtoExecutionContext(
        string testName,
        IServiceScope scope,
        ProtoTestId id,
        MethodInfo testMethod,
        ProtoTestTraceRecorder trace,
        ProtoClock? clock = null,
        ProtoClockRegistry? clockRegistry = null,
        CancellationToken cancellationToken = default)
    {
        TestName = testName ?? throw new ArgumentNullException(nameof(testName));
        _scope = scope ?? throw new ArgumentNullException(nameof(scope));
        Id = id;
        TestMethod = testMethod ?? throw new ArgumentNullException(nameof(testMethod));
        CancellationToken = cancellationToken;
        _attachments = new ProtoAttachmentCollection(TestId);
        _observations = new ProtoObservationDispatcher(_scope.ServiceProvider);
        // Resolved once: a teardown finding is recorded after the scope is disposed, so it cannot look
        // the store up lazily any more. The store itself is a root singleton and stays valid.
        _findings = _scope.ServiceProvider.GetService<ProtoFindingStore>();
        _clockRegistry = clockRegistry;
        Trace = trace;
        Clock = clock ?? new ProtoClock();
        Clock.Advanced += OnClockAdvanced;
    }

    /// <summary>
    /// Gets this test's clock. Time-dependent code reads it, and the test advances it instead of
    /// sleeping; the application under test receives it as its <see cref="TimeProvider"/>.
    /// </summary>
    public ProtoClock Clock { get; }

    private void OnClockAdvanced(ProtoClockChange change)
    {
        RecordClockState("advanced");
        Trace.WriteEvent(
            "clock.advance",
            $"Clock advanced by {change.Delta:g}",
            "ProtoTest.Core",
            attributes: new Dictionary<string, string?>
            {
                ["clock.delta"] = change.Delta.ToString("g"),
                ["clock.previousUtc"] = change.PreviousUtc.ToString("O"),
                ["clock.utcNow"] = change.CurrentUtc.ToString("O")
            },
            entityKind: ProtoTraceEntityKinds.Clock,
            entityId: $"clock:{Id.Value}");
    }

    private void RecordClockState(string change)
        => Trace.SetEntityState(
            ProtoTraceEntityKinds.Clock,
            $"clock:{Id.Value}",
            "Test clock",
            new Dictionary<string, string?>
            {
                ["clock.utcNow"] = Clock.GetUtcNow().ToString("O"),
                ["clock.timezone"] = Clock.LocalTimeZone.Id
            },
            change: change);

    public string TestName { get; }
    public MethodInfo TestMethod { get; }

    /// <summary>
    /// Gets the token for this test's lifecycle: the token a caller passed to
    /// <c>StartTestAsync(..., cancellationToken)</c>, or the runner's own token where its adapter has
    /// one (NUnit's test context, the xUnit v2 runner). MSTest, xUnit v3 and TUnit expose no token,
    /// so those adapters start with <see cref="CancellationToken.None"/>. Setup I/O that can observe
    /// it - the SQL connection open and transaction begin - passes it to the provider.
    /// </summary>
    public CancellationToken CancellationToken { get; }

    /// <summary>
    /// Numeric execution ID generated by the owning host. The string form preserves leading zeroes.
    /// </summary>
    public ProtoTestId Id { get; }
    public string TestId => Id.Value;
    public long TestNumber => Id.Number;

    /// <summary>
    /// Creates a readable name that is unique to this test and deterministic across runs, for a record
    /// that must survive the test process: a tenant, an operator, an account, a customer. The name
    /// derives from <see cref="TestId"/>, so parallel tests never collide and a rerun against a
    /// persistent store or a configured environment reuses the same record instead of guessing a new
    /// one. Use <paramref name="sequence"/> when one test creates several objects of the same kind; the
    /// default (<c>0</c>) omits it. This is the test-scoped companion of ProtoTest.Data's
    /// <c>ProtoDataValueContext.NextString()</c>, which derives generated member defaults the same way.
    /// </summary>
    /// <example>
    /// <code>
    /// var tenant = context.UniqueName("tenant");        // "tenant-0042317"
    /// var second = context.UniqueName("member", 2);     // "member-0042317-2"
    /// </code>
    /// </example>
    public string UniqueName(string name, int sequence = 0)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentOutOfRangeException.ThrowIfNegative(sequence);
        return sequence == 0 ? $"{name}-{TestId}" : $"{name}-{TestId}-{sequence}";
    }

    /// <summary>Records automatic execution diagnostics for ProtoTest integrations.</summary>
    public IProtoTraceWriter Trace { get; }

    /// <summary>Retrieves the global configuration registered in the ProtoHost.</summary>
    public IConfiguration Configuration => Service<IConfiguration>();

    public IServiceProvider Services => _scope.ServiceProvider;
    public T Service<T>() where T : notnull => Services.GetRequiredService<T>();
    public T? TryService<T>() => Services.GetService<T>();

    /// <summary>Gets a snapshot of the artifacts registered for this test.</summary>
    public IReadOnlyList<ProtoTestAttachment> Attachments => _attachments.Snapshot();

    public ProtoTestAttachment AddAttachment(
        string name,
        string content,
        string mediaType = "text/plain",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromText(name, content, mediaType, description));

    public ProtoTestAttachment AddAttachment(
        string name,
        ReadOnlyMemory<byte> content,
        string mediaType = "application/octet-stream",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromBytes(name, content, mediaType, description));

    public ProtoTestAttachment AddAttachmentFile(
        string filePath,
        string? name = null,
        string mediaType = "application/octet-stream",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromFile(filePath, name, mediaType, description));

    public ProtoTestAttachment AddAttachment(ProtoTestAttachment attachment)
    {
        var registered = _attachments.Add(attachment);
        Trace.Attachment(registered.Name, registered.MediaType, registered.Description);
        return registered;
    }

    /// <summary>Registers or replaces contextual state for this test.</summary>
    public void SetContext<T>(T context) where T : class, IProtoContext
        => SetContextCore(null, context);

    /// <summary>
    /// Registers or replaces contextual state under a key, so two protocols can store the same state
    /// type without overwriting each other's instance.
    /// </summary>
    public void SetContext<T>(string key, T context) where T : class, IProtoContext
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        SetContextCore(key, context);
    }

    private void SetContextCore<T>(string? key, T context) where T : class, IProtoContext
    {
        ArgumentNullException.ThrowIfNull(context);
        _state.Set(key, context);
        var entityId = key is null ? typeof(T).FullName! : $"{key}:{typeof(T).FullName}";
        Trace.SetEntityState(
            ProtoTraceEntityKinds.Context,
            entityId,
            key is null ? $"Context · {typeof(T).Name}" : $"Context · {key} · {typeof(T).Name}",
            new Dictionary<string, string?>
            {
                ["context.type"] = typeof(T).FullName,
                ["context.key"] = key,
                ["context.value"] = ProtoTraceValueFormatter.Serialize(context)
            },
            scope: TestName,
            change: "set");
    }

    /// <summary>Retrieves contextual state when it is present.</summary>
    public T? TryResolve<T>() where T : class, IProtoContext
    {
        return _state.TryGet<T>(key: null);
    }

    /// <summary>Retrieves contextual state registered under a key when it is present.</summary>
    public T? TryResolve<T>(string key) where T : class, IProtoContext
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        return _state.TryGet<T>(key);
    }

    /// <summary>Retrieves required contextual state.</summary>
    public T Resolve<T>() where T : class, IProtoContext => ResolveCore<T>(key: null);

    /// <summary>Retrieves required contextual state registered under a key.</summary>
    public T Resolve<T>(string key) where T : class, IProtoContext
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        return ResolveCore<T>(key);
    }

    private T ResolveCore<T>(string? key) where T : class, IProtoContext
    {
        try
        {
            return _state.Get<T>(key);
        }
        catch (Exception exception)
        {
            var entityId = key is null ? typeof(T).FullName : $"{key}:{typeof(T).FullName}";
            Trace.WriteEvent(
                "context.resolve",
                key is null ? $"Resolve context · {typeof(T).Name}" : $"Resolve context · {key} · {typeof(T).Name}",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Failed,
                attributes: new Dictionary<string, string?>
                {
                    ["context.type"] = typeof(T).FullName,
                    ["context.key"] = key
                },
                exception: exception,
                entityKind: ProtoTraceEntityKinds.Context,
                entityId: entityId);
            throw;
        }
    }

    /// <summary>
    /// Registers a named client for this test. A <see cref="ProtoClientOwnership.Context"/> client is
    /// released in reverse registration order when the test completes; a
    /// <see cref="ProtoClientOwnership.Caller"/> client is shared and its lifetime is managed elsewhere.
    /// </summary>
    public void RegisterClient<TClient>(
        TClient client,
        string name = "Default",
        ProtoClientOwnership ownership = ProtoClientOwnership.Context)
        where TClient : class
    {
        ArgumentNullException.ThrowIfNull(client);
        var owned = ownership is ProtoClientOwnership.Context;
        _clients.Register(client, name);
        var clientId = ProtoClientTrace.Id(typeof(TClient), name);
        RegisterOwned(new ProtoResource(
            clientId,
            "client",
            $"{(owned ? "Client" : "Shared client")} {typeof(TClient).Name} '{name}'",
            context => ReleaseClientAsync(client, owned)));
        Trace.SetEntityState(
            ProtoTraceEntityKinds.Client,
            clientId,
            $"{(owned ? "Client" : "Shared client")} {typeof(TClient).Name} '{name}'",
            new Dictionary<string, string?>
            {
                ["client.name"] = name,
                ["client.type"] = typeof(TClient).FullName,
                ["instance.type"] = client.GetType().FullName,
                ["client.owned"] = owned ? "true" : "false"
            },
            scope: TestName,
            change: "created");
    }

    /// <summary>Retrieves a required named client.</summary>
    public TClient Client<TClient>(string name = "Default") where TClient : class
    {
        var clientId = ProtoClientTrace.Id(typeof(TClient), name);
        try
        {
            return _clients.Get<TClient>(name);
        }
        catch (Exception exception)
        {
            Trace.WriteEvent(
                "client.resolve",
                $"Resolve · {name} ({typeof(TClient).Name})",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Failed,
                attributes: new Dictionary<string, string?>
                {
                    ["client.name"] = name,
                    ["client.type"] = typeof(TClient).FullName
                },
                exception: exception,
                entityKind: ProtoTraceEntityKinds.Client,
                entityId: clientId);
            throw;
        }
    }

    /// <summary>Retrieves a named client when it is present.</summary>
    public TClient? TryClient<TClient>(string name = "Default") where TClient : class
    {
        return _clients.TryGet<TClient>(name);
    }

    /// <summary>
    /// Replaces a named client registered for this test and takes ownership of the replacement under
    /// the same ownership. A per-test substitution points the test at a rebuilt client this way while
    /// the instance the registration replaced keeps its own teardown release, so every instance is
    /// still disposed exactly once. Passing the already-registered instance is a no-op: the instance
    /// already has an owner, and a second release would dispose it twice. The replacement is traced on
    /// the same client entity with a <c>replaced</c> change. Throws when no client is registered under
    /// the name: a replacement always follows a registration, it never creates one.
    /// </summary>
    public void ReplaceClient<TClient>(
        TClient client,
        string name = "Default",
        ProtoClientOwnership ownership = ProtoClientOwnership.Context)
        where TClient : class
    {
        ArgumentNullException.ThrowIfNull(client);
        var owned = ownership is ProtoClientOwnership.Context;
        if (!_clients.Replace(client, name))
        {
            return;
        }

        var clientId = ProtoClientTrace.Id(typeof(TClient), name);
        var generation = Interlocked.Increment(ref _clientReplacementSequence);
        RegisterOwned(new ProtoResource(
            $"{clientId}#replaced-{generation}",
            "client",
            $"Replaced client {typeof(TClient).Name} '{name}'",
            context => ReleaseClientAsync(client, owned)));
        Trace.SetEntityState(
            ProtoTraceEntityKinds.Client,
            clientId,
            $"{(owned ? "Client" : "Shared client")} {typeof(TClient).Name} '{name}'",
            new Dictionary<string, string?>
            {
                ["client.name"] = name,
                ["client.type"] = typeof(TClient).FullName,
                ["instance.type"] = client.GetType().FullName,
                ["client.owned"] = owned ? "true" : "false",
                ["client.replaced"] = "true"
            },
            scope: TestName,
            change: "replaced");
    }

    /// <summary>Registers a non-owning lookup alias for a client already registered under a scoped name.</summary>
    internal void RegisterClientAlias(Type clientType, string name, object client)
        => _clients.RegisterAlias(clientType, name, client);

    /// <summary>Looks up a client without knowing its compile-time type; used by the initializer hook.</summary>
    internal object? TryClient(Type clientType, string name)
        => _clients.TryGet(clientType, name);

    /// <summary>
    /// Finds the registration name a client was registered under, so traced operations can link to the
    /// client entity the configuration was recorded on.
    /// </summary>
    internal string? TryClientName(object client) => _clients.FindName(client);

    /// <summary>
    /// The names clients of the type are registered under for this test, in registration order; used by
    /// name resolution to complete a bare name from a uniquely named client.
    /// </summary>
    internal IReadOnlyList<string> RegisteredClientNames(Type clientType) => _clients.Names(clientType);

    /// <summary>The registered clients in registration order; used by the completion phase.</summary>
    internal IReadOnlyList<object> RegisteredClients => _clients.Snapshot();

    /// <summary>Gets a snapshot of the resources owned by this test, in registration order.</summary>
    public IReadOnlyList<ProtoResourceSnapshot> Resources => _resources.Snapshot();

    /// <summary>
    /// Registers a resource owned by this test. Owned resources are released in reverse registration
    /// order during teardown, after hooks and attributes and before clients are disposed. Resources
    /// registered here reach the run's report; framework-managed clients do not, unless their release fails.
    /// </summary>
    public void RegisterResource(IProtoResource resource)
    {
        ArgumentNullException.ThrowIfNull(resource);
        if (resource.Scope != ProtoResourceScope.Test)
        {
            throw new InvalidOperationException(
                $"Resource '{resource.Id}' is {resource.Scope}-scoped and outlives this test. " +
                "Register it with AddResource on the host builder instead.");
        }

        RegisterOwned(resource);
        _reportedResources.Add(resource.Id);
        Trace.SetEntityState(
            resource.Kind,
            resource.Id,
            $"Resource · {resource.Id}",
            new Dictionary<string, string?>
            {
                ["resource.id"] = resource.Id,
                ["resource.kind"] = resource.Kind,
                ["resource.scope"] = "test",
                ["resource.description"] = resource.Description,
                ["resource.state"] = "registered"
            },
            scope: TestName,
            change: "created");
    }

    /// <summary>Registers a resource and returns it, so ownership can be expressed inline.</summary>
    public T RegisterResource<T>(T resource) where T : class, IProtoResource
    {
        RegisterResource((IProtoResource)resource);
        return resource;
    }

    /// <summary>Registers a resource described by a release callback.</summary>
    public void RegisterResource(
        string id,
        string kind,
        string description,
        Func<ProtoResourceReleaseContext, ValueTask> release)
        => RegisterResource(new ProtoResource(id, kind, description, release));

    /// <summary>
    /// Releases one owned resource before teardown. Returns <see langword="false"/> when the resource
    /// is unknown or was already released.
    /// </summary>
    public ValueTask<bool> ReleaseResourceAsync(string id)
        => _resources.ReleaseAsync(id, this, Trace, ProtoTracePhase.Execution);

    /// <summary>
    /// Records a finding: something worth reporting that is deliberately not a test failure. Findings
    /// reach the run's reports and run gates, and are traced so they appear in ProtoTrace.
    /// </summary>
    public ProtoReportItem AddFinding(
        string message,
        ProtoReportStatus status = ProtoReportStatus.Warning,
        string? identifier = null,
        string? category = null,
        string? targetName = null,
        IReadOnlyList<string>? tags = null,
        IReadOnlyDictionary<string, object>? metadata = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(message);
        var sequence = Interlocked.Increment(ref _findingSequence);
        // One redacted copy serves the report item and the trace record: the evidence boundary applies
        // the policy once, so no axis can carry a name the other hides.
        var redactedMetadata = WithTestIdentity(ProtoMetadataRedaction.Redact(metadata));
        var item = new ProtoReportItem(
            TargetName: targetName ?? "Test findings",
            Category: category ?? "Finding",
            Identifier: identifier ?? $"finding-{sequence:D3}",
            Kind: ProtoReportItemKinds.Finding,
            Status: status,
            Message: message,
            Tags: tags,
            Metadata: redactedMetadata,
            DisplayGroup: TestName);
        _findings?.Add(item);
        Trace.Finding(message, status.ToString(), item.Category, item.TargetName, tags, redactedMetadata);
        return item;
    }

    private IReadOnlyDictionary<string, object> WithTestIdentity(IReadOnlyDictionary<string, object>? metadata)
    {
        var merged = metadata is null
            ? new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase)
            : new Dictionary<string, object>(metadata, StringComparer.OrdinalIgnoreCase);
        merged["test.id"] = TestId;
        merged["test.name"] = TestName;
        return merged;
    }

    /// <summary>Gets a snapshot of observations recorded for this test.</summary>
    public IReadOnlyCollection<ProtoObservation> RecordedObservations => _observations.Snapshot();

    /// <summary>Stores and dispatches an observation to every collector that accepts it.</summary>
    public void RecordObservation(ProtoObservation observation)
    {
        foreach (var failure in _observations.Record(observation))
        {
            // A collector bug is evidence, not a test failure: record it and let the collectors behind
            // it and the observation itself continue.
            Trace.WriteEvent(
                "collector.failed",
                $"Collector failed · {observation.Kind}",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Failed,
                attributes: new Dictionary<string, string?>
                {
                    ["observation.kind"] = observation.Kind,
                    ["observation.target"] = observation.TargetName
                },
                exception: failure);
        }

        Trace.Observation(
            observation.TargetName,
            observation.Kind,
            observation.Identifier,
            ProtoTraceValueFormatter.Serialize(observation.Data),
            ProtoTraceValueFormatter.Serialize(observation.Metadata));
    }

    /// <summary>Convenience overload for recording an observation.</summary>
    public void RecordObservation(
        string targetName,
        string kind,
        string identifier,
        object? data = null,
        IReadOnlyDictionary<string, object>? metadata = null)
        => RecordObservation(new ProtoObservation(targetName, kind, identifier, data, metadata));

    /// <summary>
    /// Releases owned resources, disposes owned clients and the service scope. Disposal is idempotent
    /// and attempts every resource.
    /// </summary>
    public ValueTask DisposeAsync() => DisposeAsync(ProtoTracePhase.Teardown);

    /// <summary>
    /// Releases owned resources, disposes owned clients and the service scope. Disposal is idempotent
    /// and attempts every resource.
    /// </summary>
    internal async ValueTask DisposeAsync(ProtoTracePhase phase)
    {
        if (Interlocked.Exchange(ref _disposeStarted, 1) != 0)
        {
            return;
        }

        // The test is over: a request that still carries its id finds the run clock from here on. The
        // registry is host-scoped, so this only removes this host's entry.
        _clockRegistry?.Remove(Id.Value);
        _clients.Seal();
        using var releaseOperation = Trace
            .Operation("resources.release", "Release owned resources", "ProtoTest.Core")
            .During(phase)
            .Begin();
        var exceptions = (await _resources.ReleaseAllAsync(this, Trace, phase)).ToList();
        if (exceptions.Count == 0)
        {
            releaseOperation.Succeed();
        }
        else
        {
            releaseOperation.Fail(new AggregateException(exceptions));
        }

        PublishOwnedResources();
        try
        {
            await LifecycleExceptionHelper.DisposeAsyncOrSync(_scope);
        }
        catch (Exception exception)
        {
            exceptions.Add(exception);
        }

        if (exceptions.Count > 0)
        {
            throw new AggregateException("One or more execution context resources failed to dispose.", exceptions);
        }
    }

    private void RegisterOwned(IProtoResource resource) => _resources.Register(resource);

    /// <summary>
    /// Publishes what this test owned, after release, so reports explain teardown. The report lists the
    /// resources the test registered; clients are framework plumbing found in the trace and viewer, and
    /// appear in the report only when their release failed.
    /// </summary>
    private void PublishOwnedResources()
    {
        if (TryService<ProtoResourceReportStore>() is not { } store)
        {
            return;
        }

        store.Add(TestName, _resources.Snapshot().Where(resource =>
            _reportedResources.Contains(resource.Id) || resource.State == ProtoResourceState.ReleaseFailed));
    }

    private static async ValueTask ReleaseClientAsync(object client, bool dispose)
    {
        if (!dispose)
        {
            return;
        }

        await LifecycleExceptionHelper.DisposeAsyncOrSync(client);
    }
}
