namespace ProtoTest.Core;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using ProtoTest.Core.Internal;
using System.Reflection;

/// <summary>
/// Provides the public per-test façade for metadata, services, state, clients, attachments, and observations.
/// </summary>
public sealed class ProtoExecutionContext : IAsyncDisposable
{
    private readonly IServiceScope _scope;
    private readonly ProtoAttachmentCollection _attachments;
    private readonly ProtoContextStateStore _state = new();
    private readonly ProtoClientRegistry _clients = new();
    private readonly ProtoObservationDispatcher _observations;
    private int _disposeStarted;

    public ProtoExecutionContext(string testName, IServiceScope scope, string testId, MethodInfo testMethod)
        : this(testName, scope, ProtoTestId.Parse(testId), testMethod)
    {
    }

    public ProtoExecutionContext(string testName, IServiceScope scope, ProtoTestId id, MethodInfo testMethod)
        : this(testName, scope, id, testMethod, new ProtoTestTraceRecorder(id.Value, testName, testMethod))
    {
    }

    internal ProtoExecutionContext(
        string testName,
        IServiceScope scope,
        ProtoTestId id,
        MethodInfo testMethod,
        ProtoTestTraceRecorder trace)
    {
        TestName = testName ?? throw new ArgumentNullException(nameof(testName));
        _scope = scope ?? throw new ArgumentNullException(nameof(scope));
        Id = id;
        TestMethod = testMethod ?? throw new ArgumentNullException(nameof(testMethod));
        _attachments = new ProtoAttachmentCollection(TestId);
        _observations = new ProtoObservationDispatcher(_scope.ServiceProvider);
        Trace = trace;
    }

    public string TestName { get; }
    public MethodInfo TestMethod { get; }

    /// <summary>
    /// Numeric execution ID generated by the owning host. The string form preserves leading zeroes.
    /// </summary>
    public ProtoTestId Id { get; }
    public string TestId => Id.Value;
    public long TestNumber => Id.Number;

    /// <summary>Records automatic execution diagnostics for ProtoTest integrations.</summary>
    public IProtoTraceWriter Trace { get; }

    /// <summary>Retrieves the global configuration registered in the ProtoHost.</summary>
    public IConfiguration Configuration => Service<IConfiguration>();

    public IServiceProvider Services => _scope.ServiceProvider;
    public T Service<T>() where T : notnull => Services.GetRequiredService<T>();
    public T? TryService<T>() => Services.GetService<T>();

    /// <summary>Gets a snapshot of the artifacts registered for this test.</summary>
    public IReadOnlyList<ProtoTestAttachment> Attachments => _attachments.Snapshot();

    public ProtoTestAttachment AddAttachment(
        string name,
        string content,
        string mediaType = "text/plain",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromText(name, content, mediaType, description));

    public ProtoTestAttachment AddAttachment(
        string name,
        ReadOnlyMemory<byte> content,
        string mediaType = "application/octet-stream",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromBytes(name, content, mediaType, description));

    public ProtoTestAttachment AddAttachmentFile(
        string filePath,
        string? name = null,
        string mediaType = "application/octet-stream",
        string? description = null)
        => AddAttachment(ProtoTestAttachment.FromFile(filePath, name, mediaType, description));

    public ProtoTestAttachment AddAttachment(ProtoTestAttachment attachment)
    {
        var registered = _attachments.Add(attachment);
        Trace.WriteEvent(
            "attachment.register",
            $"Attachment · {registered.Name}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["attachment.name"] = registered.Name,
                ["attachment.media_type"] = registered.MediaType,
                ["attachment.description"] = registered.Description,
                ["attachment.source"] = registered.IsFile ? "file" : "memory"
            });
        return registered;
    }

    /// <summary>Registers or replaces contextual state for this test.</summary>
    public void SetContext<T>(T context) where T : class, IProtoContext
    {
        _state.Set(context);
        Trace.WriteEvent(
            "context.set",
            $"Context · {typeof(T).Name}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["context.type"] = typeof(T).FullName,
                ["context.value"] = ProtoTraceValueFormatter.Serialize(context)
            });
    }

    /// <summary>Retrieves contextual state when it is present.</summary>
    public T? TryResolve<T>() where T : class, IProtoContext
    {
        var context = _state.TryGet<T>();
        Trace.WriteEvent(
            "context.try_resolve",
            $"Try context · {typeof(T).Name}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["context.type"] = typeof(T).FullName,
                ["context.found"] = (context is not null).ToString().ToLowerInvariant()
            });
        return context;
    }

    /// <summary>Retrieves required contextual state.</summary>
    public T Resolve<T>() where T : class, IProtoContext
    {
        try
        {
            var context = _state.Get<T>();
            Trace.WriteEvent(
                "context.resolve",
                $"Resolve context · {typeof(T).Name}",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Succeeded,
                attributes: new Dictionary<string, string?>
                {
                    ["context.type"] = typeof(T).FullName
                });
            return context;
        }
        catch (Exception exception)
        {
            Trace.WriteEvent(
                "context.resolve",
                $"Resolve context · {typeof(T).Name}",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Failed,
                attributes: new Dictionary<string, string?> { ["context.type"] = typeof(T).FullName },
                exception: exception);
            throw;
        }
    }

    /// <summary>
    /// Registers a named client for this test. Owned clients are disposed in reverse registration order
    /// when the test completes; pass <paramref name="disposeWithContext"/> as <see langword="false"/> for
    /// shared clients whose lifetime is managed elsewhere.
    /// </summary>
    public void RegisterClient<TClient>(TClient client, string name = "Default", bool disposeWithContext = true)
        where TClient : class
    {
        _clients.Register(client, name, disposeWithContext);
        Trace.WriteEvent(
            "client.register",
            $"Register · {name} ({typeof(TClient).Name})",
            "ProtoTest.Core",
            phase: ProtoTracePhase.Setup,
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["client.name"] = name,
                ["client.type"] = typeof(TClient).FullName,
                ["instance.type"] = client.GetType().FullName,
                ["client.owned"] = disposeWithContext ? "true" : "false"
            });
    }

    /// <summary>Retrieves a required named client.</summary>
    public TClient Client<TClient>(string name = "Default") where TClient : class
    {
        var attributes = new Dictionary<string, string?>
        {
            ["client.name"] = name,
            ["client.type"] = typeof(TClient).FullName
        };
        try
        {
            var client = _clients.Get<TClient>(name);
            Trace.WriteEvent(
                "client.resolve",
                $"Resolve · {name} ({typeof(TClient).Name})",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Succeeded,
                attributes: attributes);
            return client;
        }
        catch (Exception exception)
        {
            Trace.WriteEvent(
                "client.resolve",
                $"Resolve · {name} ({typeof(TClient).Name})",
                "ProtoTest.Core",
                outcome: ProtoTraceOutcome.Failed,
                attributes: attributes,
                exception: exception);
            throw;
        }
    }

    /// <summary>Retrieves a named client when it is present.</summary>
    public TClient? TryClient<TClient>(string name = "Default") where TClient : class
    {
        var client = _clients.TryGet<TClient>(name);
        Trace.WriteEvent(
            "client.try_resolve",
            $"Try resolve · {name} ({typeof(TClient).Name})",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["client.name"] = name,
                ["client.type"] = typeof(TClient).FullName,
                ["client.found"] = (client is not null).ToString().ToLowerInvariant()
            });
        return client;
    }

    /// <summary>Gets a snapshot of observations recorded for this test.</summary>
    public IReadOnlyCollection<ProtoObservation> RecordedObservations => _observations.Snapshot();

    /// <summary>Stores and dispatches an observation to every collector that accepts it.</summary>
    public void RecordObservation(ProtoObservation observation)
    {
        _observations.Record(observation);
        Trace.WriteEvent(
            "observation.record",
            $"Observation · {observation.Kind}",
            "ProtoTest.Core",
            outcome: ProtoTraceOutcome.Succeeded,
            attributes: new Dictionary<string, string?>
            {
                ["observation.target"] = observation.TargetName,
                ["observation.kind"] = observation.Kind,
                ["observation.identifier"] = observation.Identifier,
                ["observation.data"] = ProtoTraceValueFormatter.Serialize(observation.Data),
                ["observation.metadata"] = ProtoTraceValueFormatter.Serialize(observation.Metadata)
            });
    }

    /// <summary>Convenience overload for recording an observation.</summary>
    public void RecordObservation(
        string targetName,
        string kind,
        string identifier,
        object? data = null,
        IReadOnlyDictionary<string, object>? metadata = null)
        => RecordObservation(new ProtoObservation(targetName, kind, identifier, data, metadata));

    /// <summary>
    /// Disposes owned clients and the service scope. Disposal is idempotent and attempts every resource.
    /// </summary>
    public async ValueTask DisposeAsync()
    {
        if (Interlocked.Exchange(ref _disposeStarted, 1) != 0)
        {
            return;
        }

        var exceptions = (await _clients.DisposeClientsAsync(Trace)).ToList();
        try
        {
            if (_scope is IAsyncDisposable asyncDisposable)
            {
                await asyncDisposable.DisposeAsync();
            }
            else
            {
                _scope.Dispose();
            }
        }
        catch (Exception exception)
        {
            exceptions.Add(exception);
        }

        if (exceptions.Count > 0)
        {
            throw new AggregateException("One or more execution context resources failed to dispose.", exceptions);
        }
    }
}
