<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="HotChocolate.Subscriptions.InMemory" />
    <ProjectReference Include="..\ProtoTest.SampleApp.Contracts\ProtoTest.SampleApp.Contracts.csproj" />
    <ProjectReference Include="..\ProtoTest.SampleApp.Domain\ProtoTest.SampleApp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\northstar.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <None Update="openapi\northstar.v1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
