namespace ProtoTest.Reporting;

using ProtoTest.Core;
using System.Text;

/// <summary>
/// Writes a self-contained HTML report. The document itself is built by <see cref="HtmlReportRenderer"/> and
/// its embedded assets live in <see cref="HtmlReportAssets"/>; this sink owns the file and the options.
/// </summary>
public sealed class HtmlReportSink : FileReportSink<HtmlReportSinkOptions>
{
    public HtmlReportSink() : this(new HtmlReportSinkOptions()) { }

    public HtmlReportSink(HtmlReportSinkOptions options)
        : base(options, HtmlReportSinkOptions.ConfigurationSectionName)
    {
    }

    public string Title
    {
        get => Options.Title;
        set => Options.Title = value;
    }

    protected override string MediaType => "text/html";

    protected override string ArtifactDescription => "HTML report generated by ProtoTest.Reporting";

    protected override Task WriteAsync(
        string outputPath,
        ProtoReport report,
        CancellationToken cancellationToken)
        => File.WriteAllTextAsync(
            outputPath,
            HtmlReportRenderer.Render(report, Options.Title),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            cancellationToken);
}
