namespace ProtoTest.Reporting;

using ProtoTest.Core;
using System.Globalization;
using System.Net;
using System.Text;
using System.Text.Json;

public sealed class HtmlReportSink : FileReportSink<HtmlReportSinkOptions>
{
    private static readonly string BrandMark = ReadEmbeddedText("ProtoTest.Reporting.BrandMark.svg");

    /// <summary>
    /// The report shares one token file with the ProtoTrace viewer and the documentation, so the three
    /// surfaces cannot drift apart. The file is embedded from <c>design/prototest-tokens.css</c>.
    /// </summary>
    private static readonly string Styles = $"<style>{ReadEmbeddedText("ProtoTest.Reporting.Tokens.css")}{ComponentStyles}</style>";

    private static readonly string Favicon = "data:image/svg+xml;base64," + Convert.ToBase64String(
        Encoding.UTF8.GetBytes(ThemedForImage(BrandMark)));

    /// <summary>The viewer's expander: a plus that loses its stem when the row is open.</summary>
    private const string Expander =
        "<span class=\"chevron\" aria-hidden=\"true\"><svg viewBox=\"0 0 10 10\" width=\"10\" height=\"10\">"
        + "<path d=\"M1.6 5H8.4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
        + "<path class=\"stem\" d=\"M5 1.6V8.4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
        + "</svg></span>";

    /// <summary>
    /// The inline mark takes its colours from the page's surface tokens. A favicon is an image and cannot see
    /// them, so it carries its own light and dark fills and follows the operating system instead.
    /// </summary>
    private static string ThemedForImage(string svg)
    {
        const string style = "<style>path:nth-of-type(1){fill:#123B58}path:nth-of-type(2){fill:#1688BF}"
            + "@media (prefers-color-scheme: dark){path:nth-of-type(1){fill:#F7F5EE}path:nth-of-type(2){fill:#19A8B5}}</style>";
        var tagEnd = svg.IndexOf('>', svg.IndexOf("<svg", StringComparison.Ordinal));
        return tagEnd < 0 ? svg : svg.Insert(tagEnd + 1, style);
    }

    public HtmlReportSink() : this(new HtmlReportSinkOptions()) { }

    public HtmlReportSink(HtmlReportSinkOptions options)
        : base(options, HtmlReportSinkOptions.ConfigurationSectionName)
    {
    }

    public string Title
    {
        get => Options.Title;
        set => Options.Title = value;
    }

    protected override string MediaType => "text/html";

    protected override string ArtifactDescription => "HTML report generated by ProtoTest.Reporting";

    protected override Task WriteAsync(
        string outputPath,
        ProtoReport report,
        CancellationToken cancellationToken)
        => File.WriteAllTextAsync(outputPath, Render(report), Encoding.UTF8, cancellationToken);

    private string Render(ProtoReport report)
    {
        var html = new StringBuilder();
        html.Append("""
            <!doctype html>
            <html lang="en" data-theme="dark">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <meta name="color-scheme" content="dark light">
            """);
        html.Append("<meta name=\"theme-color\" content=\"#126AA8\"><link rel=\"icon\" type=\"image/svg+xml\" href=\"")
            .Append(Favicon)
            .Append("\">");
        html.Append("<title>").Append(Encode(Options.Title)).Append("</title>");
        html.Append(Styles);
        html.Append("""
            </head>
            <body>
            <header class="topbar">
              <div class="brand">
                <span class="brand-mark" aria-hidden="true">
            """);
        html.Append(BrandMark);
        html.Append("""
                </span>
                <span><strong>ProtoTest</strong><small>REPORTING BLUEPRINT</small></span>
              </div>
              <div class="run-state">
            """);

        var stateClass = report.Summary.Errors > 0 || report.Summary.Uncovered > 0 || report.Summary.Warnings > 0
            ? "attention"
            : "healthy";
        var stateText = report.Summary.Errors > 0
            ? $"{report.Summary.Errors} error{PluralSuffix(report.Summary.Errors)}"
            : report.Summary.Uncovered > 0
                ? $"{report.Summary.Uncovered} uncovered"
                : report.Summary.Warnings > 0
                    ? $"{report.Summary.Warnings} warning{PluralSuffix(report.Summary.Warnings)}"
                    : report.Summary.CoverageTotal > 0
                        ? "All covered"
                        : "Clean run";
        html.Append("<span class=\"state-pill ").Append(stateClass).Append("\"><i></i>")
            .Append(Encode(stateText)).Append("</span></div>");
        html.Append("""
              <div class="top-actions">
                <label class="search"><span aria-hidden="true">⌕</span><input id="reportSearch" type="search" placeholder="Search report…" autocomplete="off"><kbd>/</kbd></label>
                <button class="icon-button" id="themeToggle" type="button" aria-label="Toggle color theme" title="Toggle color theme">◐</button>
              </div>
            </header>
            <main>
              <section class="hero">
                <div>
                  <p class="eyebrow">RUN REPORT</p>
            """);
        html.Append("<h1>").Append(Encode(Options.Title)).Append("</h1>");
        html.Append("<p class=\"generated\">Generated <time datetime=\"")
            .Append(report.GeneratedAtUtc.ToString("O", CultureInfo.InvariantCulture)).Append("\">")
            .Append(Encode(report.GeneratedAtUtc.ToString("yyyy-MM-dd HH:mm:ss 'UTC'", CultureInfo.InvariantCulture)))
            .Append("</time></p></div>");

        if (report.Summary.CoverageTotal > 0)
        {
            html.Append("<div class=\"coverage-ring\" style=\"--coverage:")
                .Append(report.Summary.CoveragePercentage.ToString("0.##", CultureInfo.InvariantCulture))
                .Append("\"><span>")
                .Append(report.Summary.CoveragePercentage.ToString("0.##", CultureInfo.InvariantCulture))
                .Append("<small>%</small></span><em>coverage</em></div>");
        }

        html.Append("</section><section class=\"metrics\">");
        SummaryCard(html, "Covered", report.Summary.Covered,
            $"of {report.Summary.CoverageTotal} coverage {(report.Summary.CoverageTotal == 1 ? "entry" : "entries")}", "success");
        SummaryCard(html, "Uncovered", report.Summary.Uncovered, "Coverage gaps", "danger");
        SummaryCard(html, "Occurrences", report.Summary.TotalOccurrences, "Observed hits", "accent");
        SummaryCard(html, "Findings", report.Summary.Findings, "Recorded by tests", "warning");
        SummaryCard(html, "Run gates", report.Summary.Gates, "Run verdicts", GateTone(report.Items));
        SummaryCard(html, "Errors", report.Summary.Errors, "Failed entries", "danger");
        html.Append("""
            </section>
            <section class="report-panel">
              <div class="panel-toolbar">
                <div><h2>Report details</h2><span id="resultCount" aria-live="polite"></span></div>
                <div class="filters" role="group" aria-label="Filter report">
                  <button class="filter active" type="button" data-filter="all">All</button>
                  <button class="filter" type="button" data-filter="covered">Covered</button>
                  <button class="filter" type="button" data-filter="partial">Partial</button>
                  <button class="filter" type="button" data-filter="uncovered">Uncovered</button>
                  <button class="filter" type="button" data-filter="warning">Warnings</button>
                  <button class="filter" type="button" data-filter="error">Errors</button>
                </div>
              </div>
              <div class="report-list" id="reportList">
            """);

        RenderSections(html, report.Items);

        html.Append("""
              </div>
              <div class="empty-state" id="emptyState" hidden><strong>No matching entries</strong><span>Try another search or filter.</span></div>
            </section>
            </main>
            """);
        html.Append(Script);
        html.Append("</body></html>");
        return html.ToString();
    }

    private static void RenderItem(
        StringBuilder html,
        ProtoReportItem item,
        bool isRoot,
        int depth)
    {
        var statusClass = item.Status.ToString().ToLowerInvariant();
        var descendantItems = Flatten(item).ToArray();
        var coverageState = GetCoverageState(descendantItems);
        var coverageClass = coverageState switch
        {
            CoverageState.Covered => "covered",
            CoverageState.Partial => "partial",
            CoverageState.Uncovered => "uncovered",
            _ => "not-applicable"
        };
        var filterTokens = GetFilterTokens(descendantItems);
        var searchableText = string.Join(' ', descendantItems.SelectMany(entry => new[]
        {
            entry.Identifier,
            entry.TargetName,
            entry.Category,
            entry.Kind.ToString(),
            entry.Message ?? string.Empty,
            entry.Tags is null ? string.Empty : string.Join(' ', entry.Tags)
        })).ToLowerInvariant();

        var hasDetails = HasDetails(item);
        var container = hasDetails ? "details" : "article";

        html.Append('<').Append(container).Append(" class=\"report-item ").Append(coverageClass).Append(' ')
            .Append("status-").Append(statusClass).Append(isRoot ? " root" : " child")
            .Append("\" data-report-item=\"").Append(isRoot ? "root" : "child").Append('"');
        if (isRoot)
        {
            html.Append(" data-search=\"").Append(Encode(searchableText)).Append("\" data-filters=\"")
                .Append(filterTokens).Append('"');
        }
        if (hasDetails && depth < 1) html.Append(" open");
        html.Append('>');

        html.Append(hasDetails ? "<summary>" : "<div class=\"item-summary\">");
        html.Append(hasDetails
                ? Expander
                : "<span class=\"chevron-placeholder\" aria-hidden=\"true\"></span>")
            .Append("<span class=\"status-dot\" aria-hidden=\"true\"></span>")
            .Append("<span class=\"item-heading\"><strong");
        var displayIdentifier = GetDisplayIdentifier(item);
        if (!string.Equals(displayIdentifier, item.Identifier, StringComparison.Ordinal))
        {
            html.Append(" title=\"").Append(Encode(item.Identifier)).Append('"');
        }
        html.Append('>').Append(Encode(displayIdentifier)).Append("</strong>")
            .Append("<span class=\"item-context\">").Append(Encode(GetContextLabel(item, isRoot)))
            .Append("</span></span>")
            .Append("<span class=\"item-badges\">");

        if (coverageState != CoverageState.NotApplicable)
        {
            html.Append("<span class=\"badge coverage-badge\">")
                .Append(coverageState).Append("</span>");
        }
        if (item.Kind == ProtoReportItemKind.Gate || item.Status != ProtoReportStatus.Neutral)
        {
            html.Append("<span class=\"badge status-badge\">").Append(Encode(GetStatusLabel(item))).Append("</span>");
        }
        if (item.Count > 0 && item.Kind is ProtoReportItemKind.Coverage or ProtoReportItemKind.Observation)
        {
            html.Append("<span class=\"badge\">").Append(item.Count.ToString(CultureInfo.InvariantCulture))
                .Append(" occurrence").Append(PluralSuffix(item.Count)).Append("</span>");
        }
        html.Append(hasDetails ? "</span></summary><div class=\"item-body\">" : "</span></div>");

        if (!hasDetails)
        {
            html.Append("</article>");
            return;
        }

        if (item.Value is not null)
        {
            html.Append("<div class=\"measured-value\"><strong>")
                .Append(item.Value.Value.ToString(CultureInfo.InvariantCulture)).Append("</strong><span>")
                .Append(Encode(item.Unit)).Append("</span></div>");
        }
        if (!string.IsNullOrWhiteSpace(item.Message))
        {
            html.Append("<p class=\"message\">").Append(Encode(item.Message)).Append("</p>");
        }
        if (item.Tags is { Count: > 0 })
        {
            html.Append("<div class=\"tags\">");
            foreach (var tag in item.Tags)
            {
                html.Append("<span class=\"tag\">#").Append(Encode(tag)).Append("</span>");
            }
            html.Append("</div>");
        }
        if (item.Metadata is { Count: > 0 })
        {
            html.Append("<details class=\"metadata\"><summary>Metadata</summary><pre>")
                .Append(Encode(JsonSerializer.Serialize(item.Metadata, new JsonSerializerOptions { WriteIndented = true })))
                .Append("</pre></details>");
        }
        if (item.Children is { Count: > 0 })
        {
            html.Append("<div class=\"children\">");
            foreach (var child in item.Children)
            {
                RenderItem(html, child, isRoot: false, depth + 1);
            }
            html.Append("</div>");
        }
        html.Append("</div></details>");
    }

    private static bool HasDetails(ProtoReportItem item)
        => item.Value is not null
            || !string.IsNullOrWhiteSpace(item.Message)
            || item.Tags is { Count: > 0 }
            || item.Metadata is { Count: > 0 }
            || item.Children is { Count: > 0 };

    private static string GetDisplayIdentifier(ProtoReportItem item)
        => item.DisplayName ?? item.Identifier;

    /// <summary>
    /// Gates speak their own language: a gate does not succeed or error, it passes, advises or fails.
    /// </summary>
    private static string GetStatusLabel(ProtoReportItem item)
        => item.Kind != ProtoReportItemKind.Gate
            ? item.Status.ToString()
            : item.Status switch
            {
                ProtoReportStatus.Success => "Passed",
                ProtoReportStatus.Warning => "Warning",
                ProtoReportStatus.Error => "Failed",
                ProtoReportStatus.Info => "Info",
                _ => "Skipped"
            };

    private static string GetContextLabel(ProtoReportItem item, bool isRoot)
    {
        if (item.Kind == ProtoReportItemKind.Gate)
        {
            return "Run gate";
        }

        if (item.Kind == ProtoReportItemKind.Finding)
        {
            return item.DisplayGroup is { Length: > 0 }
                ? $"{item.Category} · {item.DisplayGroup}"
                : item.Category;
        }

        var category = item.DisplayGroup ?? item.Category;
        return isRoot ? $"{item.TargetName} · {category}" : category;
    }

    /// <summary>
    /// Report items are different things, so the report keeps them in different categories rather
    /// than one undifferentiated list: coverage, findings, run verdicts, metrics and observations.
    /// </summary>
    private static readonly (ProtoReportItemKind Kind, string Title)[] Sections =
    [
        (ProtoReportItemKind.Coverage, "Coverage"),
        (ProtoReportItemKind.Finding, "Findings"),
        (ProtoReportItemKind.Gate, "Run gates"),
        (ProtoReportItemKind.Metric, "Metrics"),
        (ProtoReportItemKind.Observation, "Observations")
    ];

    private static void RenderSections(StringBuilder html, IReadOnlyList<ProtoReportItem> items)
    {
        foreach (var (kind, title) in Sections)
        {
            var roots = items.Where(item => item.Kind == kind).ToArray();
            if (roots.Length == 0) continue;

            html.Append("<section class=\"report-section\" data-report-section data-kind=\"")
                .Append(kind.ToString().ToLowerInvariant())
                .Append("\"><header class=\"section-head\"><i aria-hidden=\"true\"></i><h3>")
                .Append(Encode(title)).Append("</h3><span class=\"section-count\" data-section-count data-total=\"")
                .Append(roots.Length.ToString(CultureInfo.InvariantCulture)).Append("\">")
                .Append(roots.Length.ToString(CultureInfo.InvariantCulture)).Append(PluralSuffix(roots.Length, " entry", " entries"))
                .Append("</span></header>");

            foreach (var item in roots)
            {
                RenderItem(html, item, isRoot: true, depth: 0);
            }

            html.Append("</section>");
        }
    }

    private static string GateTone(IEnumerable<ProtoReportItem> items)
    {
        var gates = items.SelectMany(Flatten).Where(item => item.Kind == ProtoReportItemKind.Gate).ToArray();
        if (gates.Length == 0) return "neutral";
        if (gates.Any(item => item.Status == ProtoReportStatus.Error)) return "danger";
        if (gates.Any(item => item.Status == ProtoReportStatus.Warning)) return "warning";
        return "success";
    }

    private static string GetFilterTokens(IEnumerable<ProtoReportItem> items)
    {
        var materializedItems = items.ToArray();
        var tokens = new HashSet<string>(StringComparer.Ordinal);
        if (GetCoverageState(materializedItems) == CoverageState.Partial)
        {
            tokens.Add("partial");
        }
        foreach (var item in materializedItems)
        {
            if (item.IsCovered is true) tokens.Add("covered");
            if (item.IsCovered is false) tokens.Add("uncovered");
            if (item.Status == ProtoReportStatus.Warning) tokens.Add("warning");
            if (item.Status == ProtoReportStatus.Error) tokens.Add("error");
        }

        return string.Join(' ', tokens);
    }

    private static CoverageState GetCoverageState(IEnumerable<ProtoReportItem> items)
    {
        var hasCovered = false;
        var hasUncovered = false;
        foreach (var item in items.Where(item => item.Kind == ProtoReportItemKind.Coverage))
        {
            hasCovered |= item.IsCovered is true;
            hasUncovered |= item.IsCovered is false;
        }

        if (hasCovered && hasUncovered) return CoverageState.Partial;
        if (hasCovered) return CoverageState.Covered;
        if (hasUncovered) return CoverageState.Uncovered;
        return CoverageState.NotApplicable;
    }

    private static IEnumerable<ProtoReportItem> Flatten(ProtoReportItem item)
    {
        yield return item;
        if (item.Children is null) yield break;
        foreach (var child in item.Children)
        {
            foreach (var descendant in Flatten(child)) yield return descendant;
        }
    }

    private static void SummaryCard(
        StringBuilder html,
        string label,
        int value,
        string description,
        string tone)
    {
        html.Append("<article class=\"metric ").Append(tone).Append("\"><span>").Append(Encode(label))
            .Append(value == 0 ? "</span><strong data-zero>" : "</span><strong>").Append(value.ToString(CultureInfo.InvariantCulture))
            .Append("</strong><small>").Append(Encode(description)).Append("</small></article>");
    }

    private static string PluralSuffix(int count) => count == 1 ? string.Empty : "s";

    private static string PluralSuffix(int count, string singular, string plural)
        => count == 1 ? singular : plural;

    private static string Encode(string? value) => WebUtility.HtmlEncode(value ?? string.Empty);

    private enum CoverageState
    {
        NotApplicable,
        Covered,
        Partial,
        Uncovered
    }

    private const string ComponentStyles = """
        /* The report speaks the ProtoTrace viewer's grammar: the same tokens, panels, chips, pills, rows and
           brand mark. Every value comes from design/prototest-tokens.css, embedded above this sheet. */
        * { box-sizing: border-box; }
        html, body { margin: 0; min-height: 100%; }
        body {
          color: var(--text);
          font: var(--text-body)/var(--leading) var(--font-ui);
          background-color: var(--bg);
          background-image: linear-gradient(var(--grid-line) 1px, transparent 1px), linear-gradient(90deg, var(--grid-line) 1px, transparent 1px);
          background-size: var(--grid-size) var(--grid-size);
          -webkit-font-smoothing: antialiased;
        }
        * { scrollbar-width: thin; scrollbar-color: var(--border-strong) transparent; }
        *::-webkit-scrollbar { width: 10px; height: 10px; }
        *::-webkit-scrollbar-track { background: transparent; }
        *::-webkit-scrollbar-thumb { min-height: 36px; border: 2px solid transparent; border-radius: var(--radius-chip); background: var(--border-strong); background-clip: padding-box; }
        *::-webkit-scrollbar-thumb:hover { background-color: var(--blueprint); }
        *::-webkit-scrollbar-corner { background: transparent; }
        button, input { color: inherit; font: inherit; }
        button { cursor: pointer; }
        :focus-visible { outline: 2px solid var(--blueprint); outline-offset: 2px; border-radius: var(--radius-chip); }
        h1, h2, h3 { margin: 0; font-family: var(--font-display); font-weight: var(--weight-bold); letter-spacing: -.01em; }
        p { margin: 0; }
        .eyebrow { margin: 0; color: var(--dim); font-size: var(--text-meta); letter-spacing: var(--tracking-eyebrow); text-transform: uppercase; }

        /* ── Header: the viewer's header, with the report's own search ─────────────────────────────── */
        .topbar {
          position: sticky;
          top: 0;
          z-index: 20;
          min-height: 56px;
          padding: var(--space-3) clamp(12px, 2vw, 24px);
          display: grid;
          grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr);
          align-items: center;
          gap: var(--space-4);
          border-bottom: 1px solid var(--border);
          background: var(--surface);
        }
        .brand { min-width: 0; display: flex; align-items: center; gap: var(--space-3); }
        .brand-mark { width: 32px; height: 32px; flex: none; display: block; }
        .brand-mark svg { width: 100%; height: 100%; display: block; overflow: visible; }
        /* One mark, coloured by the surface: navy on paper, paper on the blueprint. */
        .brand-mark svg path:nth-of-type(1) { fill: var(--brand-mark-body); }
        .brand-mark svg path:nth-of-type(2) { fill: var(--brand-mark-check); }
        .brand > span:last-child { min-width: 0; display: flex; flex-direction: column; line-height: var(--leading-tight); }
        .brand strong { font-family: var(--font-display); font-size: var(--text-title); letter-spacing: .01em; }
        .brand small { color: var(--dim); font-size: var(--text-micro); letter-spacing: var(--tracking-eyebrow); text-transform: uppercase; }
        .run-state { justify-self: center; }
        /* An outcome is a dot and a word, as in the viewer: no pill, no glow. */
        .state-pill { display: inline-flex; align-items: center; gap: var(--space-2); color: var(--success); font-size: var(--text-meta); font-weight: var(--weight-semibold); white-space: nowrap; }
        .state-pill i { width: 7px; height: 7px; border-radius: 50%; background: currentColor; }
        .state-pill.attention { color: var(--danger); }
        .top-actions { justify-self: end; display: flex; align-items: center; gap: var(--space-3); }
        .search {
          width: 260px;
          height: var(--control-height);
          padding: 0 var(--space-3);
          display: flex;
          align-items: center;
          gap: var(--space-2);
          border: 1px solid var(--border);
          border-radius: var(--radius-control);
          background: var(--surface-2);
          color: var(--dim);
        }
        .search:hover { border-color: var(--border-strong); }
        .search:focus-within { border-color: var(--blueprint); box-shadow: 0 0 0 3px var(--blueprint-soft); }
        .search input { min-width: 0; flex: 1; border: 0; outline: 0; background: transparent; color: var(--text); font-size: var(--text-meta); }
        .search input::placeholder { color: var(--dim); }
        .search kbd { padding: 0 var(--space-1); border: 1px solid var(--border); border-radius: var(--radius-chip); color: var(--muted); font: var(--text-micro) var(--font-mono); }
        .icon-button {
          width: var(--control-height);
          height: var(--control-height);
          display: grid;
          place-items: center;
          padding: 0;
          border: 1px solid var(--border-strong);
          border-radius: var(--radius-control);
          background: var(--surface-2);
          color: var(--text);
          font-size: var(--text-title);
          line-height: 1;
        }
        .icon-button:hover { border-color: var(--blueprint); }

        /* ── Run heading and metrics ────────────────────────────────────────────────────────────────── */
        main { width: min(1240px, 100% - var(--space-7)); margin: 0 auto var(--space-7); display: grid; gap: var(--space-4); }
        .hero { padding-top: var(--space-6); display: flex; flex-wrap: wrap; align-items: flex-end; justify-content: space-between; gap: var(--space-5); }
        .hero h1 { margin: var(--space-1) 0; font-size: var(--text-display); letter-spacing: var(--tracking-display); }
        .generated { color: var(--muted); font: var(--text-body) var(--font-mono); }
        .coverage-ring {
          --coverage: 0;
          width: 84px;
          height: 84px;
          position: relative;
          display: grid;
          place-items: center;
          border-radius: 50%;
          background: conic-gradient(var(--success) calc(var(--coverage) * 1%), var(--surface-2) 0);
        }
        .coverage-ring::before { content: ""; position: absolute; inset: 6px; border-radius: inherit; background: var(--bg); }
        .coverage-ring span, .coverage-ring em { position: relative; z-index: 1; }
        .coverage-ring span { margin-top: -10px; font: var(--weight-bold) var(--text-title)/1 var(--font-mono); }
        .coverage-ring small { color: var(--muted); font-size: var(--text-meta); }
        .coverage-ring em { position: absolute; top: 48px; color: var(--dim); font-size: var(--text-micro); font-style: normal; letter-spacing: .08em; text-transform: uppercase; }
        /* The viewer's metric tile: label, a mono value coloured only when it means something, a caption. */
        .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: var(--space-2); }
        .metric { min-width: 0; min-height: 52px; padding: var(--space-2) var(--space-4); display: grid; gap: 1px; border: 1px solid var(--border); border-radius: var(--radius-control); background: var(--surface); }
        .metric > span { color: var(--muted); font-size: var(--text-meta); }
        .metric > strong { font: var(--weight-bold) var(--text-title) var(--font-mono); }
        .metric > small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--dim); font-size: var(--text-micro); }
        .metric.success > strong { color: var(--success); }
        .metric.warning > strong { color: var(--warning); }
        .metric.danger > strong { color: var(--danger); }
        .metric.accent > strong { color: var(--blueprint); }
        /* A zero is not a warning: colour only numbers that carry news. */
        .metric > strong:is(:empty, [data-zero]) { color: var(--text); }

        /* ── The panel, its toolbar and the filter chips ────────────────────────────────────────────── */
        .report-panel { border: 1px solid var(--border); border-radius: var(--radius-panel); background: var(--surface); overflow: hidden; }
        .panel-toolbar {
          min-height: var(--panel-head-height);
          padding: var(--space-2) var(--space-4);
          display: flex;
          flex-wrap: wrap;
          align-items: center;
          justify-content: space-between;
          gap: var(--space-2) var(--space-4);
          border-bottom: 1px solid var(--border);
        }
        .panel-toolbar > div:first-child { display: flex; align-items: baseline; gap: var(--space-3); }
        .panel-toolbar h2 { font-family: var(--font-ui); font-size: var(--text-strong); }
        .panel-toolbar #resultCount { color: var(--muted); font: var(--text-micro) var(--font-mono); }
        .filters { display: flex; flex-wrap: wrap; gap: var(--space-1); }
        .filter {
          height: 24px;
          padding: 0 var(--space-3);
          display: inline-flex;
          align-items: center;
          border: 1px solid var(--border);
          border-radius: var(--radius-pill);
          background: transparent;
          color: var(--muted);
          font-size: var(--text-micro);
          transition: border-color var(--motion-fast) var(--motion-ease), color var(--motion-fast) var(--motion-ease);
        }
        .filter:hover { border-color: var(--border-strong); color: var(--text); }
        .filter.active { border-color: var(--blueprint); background: var(--blueprint-soft); color: var(--text); font-weight: var(--weight-bold); }
        .filter.active[data-filter="covered"] { border-color: var(--success-line); background: var(--success-soft); }
        .filter.active[data-filter="partial"], .filter.active[data-filter="warning"] { border-color: var(--warning-line); background: var(--warning-soft); }
        .filter.active[data-filter="uncovered"], .filter.active[data-filter="error"] { border-color: var(--danger-line); background: var(--danger-soft); }

        /* ── Sections: a heading per kind of result, as the viewer heads its phases ─────────────────── */
        .report-list { padding: 0 var(--space-3) var(--space-4); }
        .report-section[hidden] { display: none; }
        .report-section + .report-section { margin-top: var(--space-5); }
        .section-head {
          position: sticky;
          top: 56px;
          z-index: 1;
          padding: var(--space-2);
          display: grid;
          grid-template-columns: 8px minmax(0, 1fr) auto;
          align-items: center;
          gap: var(--space-3);
          border-bottom: 1px solid var(--border);
          background: var(--surface);
        }
        .section-head i { width: 8px; height: 8px; border-radius: var(--radius-hairline); background: var(--dim); }
        .section-head h3 { color: var(--muted); font-family: var(--font-ui); font-size: var(--text-micro); letter-spacing: .08em; text-transform: uppercase; }
        .section-head .section-count { color: var(--dim); font: var(--text-micro) var(--font-mono); }
        .report-section[data-kind=coverage] .section-head i { background: var(--type-evidence); }
        .report-section[data-kind=finding] .section-head i { background: var(--type-finding); }
        .report-section[data-kind=gate] .section-head i { background: var(--type-gate); }
        .report-section[data-kind=metric] .section-head i { background: var(--type-data); }
        .report-section[data-kind=observation] .section-head i { background: var(--type-observation); }
        .report-section > .report-item.root:first-of-type { margin-top: var(--space-2); }

        /* ── Items: rows, with the viewer's expander, status dot and chips ──────────────────────────── */
        .report-item { border: 1px solid transparent; border-radius: var(--radius-control); }
        .report-item.root + .report-item.root { margin-top: 1px; }
        .report-item[hidden] { display: none; }
        .report-item[open].root { border-color: var(--border); background: var(--surface-2); }
        .report-item > summary, .report-item > .item-summary {
          min-height: 34px;
          padding: var(--space-1) var(--space-2);
          display: flex;
          align-items: center;
          gap: var(--space-3);
          border-radius: var(--radius-control);
          list-style: none;
        }
        .report-item > summary { cursor: pointer; }
        .report-item > summary::-webkit-details-marker { display: none; }
        .report-item > summary:hover { background: var(--hover); }
        .chevron, .chevron-placeholder { width: 14px; height: 14px; flex: none; }
        .chevron { display: grid; place-items: center; border: 1px solid var(--border-strong); border-radius: var(--radius-hairline); background: var(--surface); color: var(--muted); }
        .report-item > summary:hover .chevron { border-color: var(--blueprint); color: var(--text); }
        .chevron .stem { transition: opacity var(--motion-fast) var(--motion-ease); }
        .report-item[open] > summary .chevron .stem { opacity: 0; }
        .status-dot { width: 7px; height: 7px; flex: none; border-radius: 50%; background: var(--success); }
        .uncovered > summary .status-dot, .uncovered > .item-summary .status-dot,
        .status-error > summary .status-dot, .status-error > .item-summary .status-dot { background: var(--danger); }
        .partial > summary .status-dot, .partial > .item-summary .status-dot,
        .status-warning > summary .status-dot, .status-warning > .item-summary .status-dot { background: var(--warning); }
        .not-applicable.status-neutral > summary .status-dot, .not-applicable.status-neutral > .item-summary .status-dot { background: var(--dim); }
        .item-heading { min-width: 0; flex: 1; display: flex; flex-direction: column; }
        .item-heading strong { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: var(--text-body); font-weight: var(--weight-semibold); }
        .item-context { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--dim); font-size: var(--text-micro); }
        .item-badges { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: var(--space-1); }
        /* Badges are the viewer's chips: mono, square-cornered, tinted by what they say. */
        .badge, .tag {
          padding: 0 var(--space-2);
          display: inline-flex;
          align-items: center;
          border-radius: var(--radius-chip);
          background: color-mix(in srgb, var(--muted) 14%, transparent);
          color: var(--muted);
          font: var(--weight-semibold) var(--text-micro)/1.8 var(--font-mono);
          white-space: nowrap;
        }
        .covered > summary .coverage-badge, .covered > .item-summary .coverage-badge { background: var(--success-soft); color: var(--success); }
        .partial > summary .coverage-badge, .partial > .item-summary .coverage-badge { background: var(--warning-soft); color: var(--warning); }
        .uncovered > summary .coverage-badge, .uncovered > .item-summary .coverage-badge { background: var(--danger-soft); color: var(--danger); }
        .status-success > summary .status-badge, .status-success > .item-summary .status-badge { background: var(--success-soft); color: var(--success); }
        .status-warning > summary .status-badge, .status-warning > .item-summary .status-badge { background: var(--warning-soft); color: var(--warning); }
        .status-error > summary .status-badge, .status-error > .item-summary .status-badge { background: var(--danger-soft); color: var(--danger); }
        /* On a coverage row, "Covered" already says it went well; a second "Success" chip is noise. */
        .status-success > summary .coverage-badge + .status-badge, .status-success > .item-summary .coverage-badge + .status-badge { display: none; }
        .item-body { padding: 0 var(--space-3) var(--space-3) calc(var(--space-2) + 14px + var(--space-3)); display: grid; gap: var(--space-3); }
        .report-item:not([open]) > .item-body { display: none; }
        .message { padding: var(--space-2) var(--space-3); border-left: 2px solid var(--blueprint); border-radius: 0 var(--radius-chip) var(--radius-chip) 0; background: var(--blueprint-soft); font-size: var(--text-meta); white-space: pre-wrap; }
        .status-warning > .item-body > .message { border-color: var(--warning); background: var(--warning-soft); }
        .status-error > .item-body > .message { border-color: var(--danger); background: var(--danger-soft); }
        .measured-value { display: flex; align-items: baseline; gap: var(--space-2); }
        .measured-value strong { font: var(--weight-bold) var(--text-heading) var(--font-mono); }
        .measured-value span { color: var(--muted); font-size: var(--text-meta); }
        .tags { display: flex; flex-wrap: wrap; gap: var(--space-1); }
        .tag { background: var(--blueprint-soft); color: var(--blueprint); }
        .metadata > summary { width: max-content; color: var(--muted); font-size: var(--text-micro); cursor: pointer; }
        .metadata pre {
          max-height: 320px;
          margin: var(--space-2) 0 0;
          padding: var(--space-3);
          overflow: auto;
          border-radius: var(--radius-chip);
          background: var(--surface-sunken);
          color: var(--text-on-sunken);
          font: var(--text-micro)/1.6 var(--font-mono);
        }
        /* Children hang off a drawn guide, the same branch language the viewer's tree uses. */
        .children { margin-left: 6px; padding-left: var(--space-3); display: grid; gap: 1px; border-left: 1px solid var(--border); }
        .report-item.child > summary, .report-item.child > .item-summary { min-height: 28px; }
        .empty-state { padding: var(--space-7) var(--space-4); display: grid; gap: var(--space-1); text-align: center; }
        /* A display on the element would otherwise beat the hidden attribute the script toggles. */
        .empty-state[hidden] { display: none; }
        .empty-state strong { font-size: var(--text-body); }
        .empty-state span { color: var(--muted); font-size: var(--text-meta); }

        @media (max-width: 1000px) {
          .topbar { grid-template-columns: minmax(0, 1fr) auto; }
          .run-state { display: none; }
        }
        @media (max-width: 720px) {
          .search { width: min(45vw, 220px); }
          .hero { padding-top: var(--space-5); }
          .item-badges .badge:not(.coverage-badge):not(.status-badge) { display: none; }
          .item-body { padding-left: var(--space-3); }
        }
        @media (max-width: 440px) {
          .brand > span:last-child, .search kbd { display: none; }
          .coverage-ring { width: 72px; height: 72px; }
          .coverage-ring em { top: 43px; }
          .item-context { display: none; }
        }
        """;

    private static string ReadEmbeddedText(string resourceName)
    {
        using var stream = typeof(HtmlReportSink).Assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded reporting asset '{resourceName}' was not found.");
        using var reader = new StreamReader(stream, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private const string Script = """
        <script>
        (() => {
          const root = document.documentElement;
          const search = document.getElementById('reportSearch');
          const entries = [...document.querySelectorAll('[data-report-item="root"]')];
          const sections = [...document.querySelectorAll('[data-report-section]')];
          const filters = [...document.querySelectorAll('[data-filter]')];
          const count = document.getElementById('resultCount');
          const empty = document.getElementById('emptyState');
          let activeFilter = 'all';

          let savedTheme;
          try { savedTheme = localStorage.getItem('prototest-report-theme'); } catch { }
          root.dataset.theme = savedTheme || (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark');
          document.getElementById('themeToggle').addEventListener('click', () => {
            root.dataset.theme = root.dataset.theme === 'dark' ? 'light' : 'dark';
            try { localStorage.setItem('prototest-report-theme', root.dataset.theme); } catch { }
          });

          function applyFilters() {
            const query = search.value.trim().toLocaleLowerCase();
            let visible = 0;
            for (const section of sections) {
              const sectionEntries = [...section.querySelectorAll('[data-report-item="root"]')];
              let sectionVisible = 0;
              for (const entry of sectionEntries) {
                const matchesText = !query || entry.dataset.search.includes(query);
                const matchesFilter = activeFilter === 'all' || entry.dataset.filters.split(' ').includes(activeFilter);
                entry.hidden = !(matchesText && matchesFilter);
                if (!entry.hidden) sectionVisible++;
              }
              section.hidden = sectionVisible === 0;
              const counter = section.querySelector('[data-section-count]');
              const total = Number(counter.dataset.total);
              counter.textContent = sectionVisible === total
                ? `${total} ${total === 1 ? 'entry' : 'entries'}`
                : `${sectionVisible} of ${total} entries`;
              visible += sectionVisible;
            }
            count.textContent = `${visible} of ${entries.length} shown`;
            empty.hidden = visible !== 0;
          }

          search.addEventListener('input', applyFilters);
          for (const filter of filters) {
            filter.addEventListener('click', () => {
              activeFilter = filter.dataset.filter;
              for (const button of filters) button.classList.toggle('active', button === filter);
              applyFilters();
            });
          }
          document.addEventListener('keydown', event => {
            if (event.key === '/' && document.activeElement !== search) {
              event.preventDefault();
              search.focus();
            }
            if (event.key === 'Escape' && document.activeElement === search) {
              search.value = '';
              search.blur();
              applyFilters();
            }
          });
          applyFilters();
        })();
        </script>
        """;
}
