namespace ProtoTest.Reporting;

using ProtoTest.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

public sealed class JsonReportSink : FileReportSink<JsonReportSinkOptions>
{
    public JsonReportSink() : this(new JsonReportSinkOptions()) { }

    public JsonReportSink(JsonReportSinkOptions options)
        : base(options, JsonReportSinkOptions.ConfigurationSectionName)
    {
    }

    public bool Indented
    {
        get => Options.Indented;
        set => Options.Indented = value;
    }

    protected override string MediaType => "application/json";

    protected override string ArtifactDescription => "JSON report generated by ProtoTest.Reporting";

    protected override async Task WriteAsync(
        string outputPath,
        ProtoReport report,
        CancellationToken cancellationToken)
    {
        var serializerOptions = new JsonSerializerOptions { WriteIndented = Options.Indented };
        serializerOptions.Converters.Add(new JsonStringEnumConverter());

        await using var stream = File.Create(outputPath);
        await JsonSerializer.SerializeAsync(stream, report, serializerOptions, cancellationToken)
            .ConfigureAwait(false);
    }
}
