<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DefineConstants>$(DefineConstants);XUNIT3</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\ProtoTest.Xunit3\ProtoTest.Xunit3.csproj" />
  </ItemGroup>
</Project>
