namespace ProtoTest.Reporting;

using ProtoTest.Core;
using System.Globalization;
using System.Net;
using System.Text;
using System.Text.Json;

public sealed class HtmlReportSink : IProtoSink, IProtoSinkArtifactSource, IProtoConfigurableOptions
{
    private static readonly string BrandMark = ReadEmbeddedText("ProtoTest.Reporting.BrandMark.svg");
    private static readonly string Favicon = "data:image/svg+xml;base64," + Convert.ToBase64String(
        Encoding.UTF8.GetBytes(ReadEmbeddedText("ProtoTest.Reporting.BlueprintMark.svg")));
    private readonly HtmlReportSinkOptions _options;
    private string? _lastOutputPath;

    public HtmlReportSink() : this(new HtmlReportSinkOptions()) { }

    public HtmlReportSink(HtmlReportSinkOptions options)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
    }

    string IProtoConfigurableOptions.ConfigurationSectionName => HtmlReportSinkOptions.ConfigurationSectionName;

    public string OutputPath
    {
        get => _options.OutputPath;
        set => _options.OutputPath = value;
    }

    public string Title
    {
        get => _options.Title;
        set => _options.Title = value;
    }

    public async Task ExportAsync(
        IEnumerable<ProtoReportItem> items,
        CancellationToken cancellationToken = default)
    {
        var outputPath = Path.GetFullPath(_options.OutputPath);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        await File.WriteAllTextAsync(
            outputPath,
            Render(ProtoReport.Create(items)),
            Encoding.UTF8,
            cancellationToken);
        _lastOutputPath = outputPath;
    }

    public IReadOnlyCollection<ProtoTestAttachment> GetArtifacts()
        => _lastOutputPath is null || !File.Exists(_lastOutputPath)
            ? []
            : [ProtoTestAttachment.FromFile(_lastOutputPath, mediaType: "text/html", description: "HTML report generated by ProtoTest.Reporting")];

    private string Render(ProtoReport report)
    {
        var html = new StringBuilder();
        html.Append("""
            <!doctype html>
            <html lang="en" data-theme="dark">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <meta name="color-scheme" content="dark light">
            """);
        html.Append("<meta name=\"theme-color\" content=\"#126AA8\"><link rel=\"icon\" type=\"image/svg+xml\" href=\"")
            .Append(Favicon)
            .Append("\">");
        html.Append("<title>").Append(Encode(_options.Title)).Append("</title>");
        html.Append(Styles);
        html.Append("""
            </head>
            <body>
            <header class="topbar">
              <div class="brand">
                <span class="brand-mark" aria-hidden="true">
            """);
        html.Append(BrandMark);
        html.Append("""
                </span>
                <span><strong>ProtoTest</strong><small>REPORTING BLUEPRINT</small></span>
              </div>
              <div class="run-state">
            """);

        var stateClass = report.Summary.Errors > 0 || report.Summary.Uncovered > 0 || report.Summary.Warnings > 0
            ? "attention"
            : "healthy";
        var stateText = report.Summary.Errors > 0
            ? $"{report.Summary.Errors} error{Plural(report.Summary.Errors)}"
            : report.Summary.Uncovered > 0
                ? $"{report.Summary.Uncovered} uncovered"
                : report.Summary.Warnings > 0
                    ? $"{report.Summary.Warnings} warning{Plural(report.Summary.Warnings)}"
                    : "All covered";
        html.Append("<span class=\"state-pill ").Append(stateClass).Append("\"><i></i>")
            .Append(Encode(stateText)).Append("</span></div>");
        html.Append("""
              <div class="top-actions">
                <label class="search"><span aria-hidden="true">⌕</span><input id="reportSearch" type="search" placeholder="Search report…" autocomplete="off"><kbd>/</kbd></label>
                <button class="icon-button" id="themeToggle" type="button" aria-label="Toggle color theme" title="Toggle color theme">◐</button>
              </div>
            </header>
            <main>
              <section class="hero">
                <div>
                  <p class="eyebrow">OBSERVATION / COVERAGE</p>
            """);
        html.Append("<h1>").Append(Encode(_options.Title)).Append("</h1>");
        html.Append("<p class=\"generated\">Generated <time datetime=\"")
            .Append(report.GeneratedAtUtc.ToString("O", CultureInfo.InvariantCulture)).Append("\">")
            .Append(Encode(report.GeneratedAtUtc.ToString("yyyy-MM-dd HH:mm:ss 'UTC'", CultureInfo.InvariantCulture)))
            .Append("</time></p></div>");

        if (report.Summary.CoverageTotal > 0)
        {
            html.Append("<div class=\"coverage-ring\" style=\"--coverage:")
                .Append(report.Summary.CoveragePercentage.ToString("0.##", CultureInfo.InvariantCulture))
                .Append("\"><span>")
                .Append(report.Summary.CoveragePercentage.ToString("0.##", CultureInfo.InvariantCulture))
                .Append("<small>%</small></span><em>coverage</em></div>");
        }

        html.Append("</section><section class=\"metrics\">");
        SummaryCard(html, "Items", report.Summary.Total, "All report entries", "accent");
        SummaryCard(html, "Covered", report.Summary.Covered, $"of {report.Summary.CoverageTotal} coverage entries", "success");
        SummaryCard(html, "Uncovered", report.Summary.Uncovered, "Coverage gaps", "danger");
        SummaryCard(html, "Occurrences", report.Summary.TotalOccurrences, "Observed events", "neutral");
        SummaryCard(html, "Warnings", report.Summary.Warnings, "Need review", "warning");
        SummaryCard(html, "Errors", report.Summary.Errors, "Failed observations", "danger");
        html.Append("""
            </section>
            <section class="report-panel">
              <div class="panel-toolbar">
                <div><h2>Report details</h2><span id="resultCount" aria-live="polite"></span></div>
                <div class="filters" role="group" aria-label="Filter report">
                  <button class="filter active" type="button" data-filter="all">All</button>
                  <button class="filter" type="button" data-filter="covered">Covered</button>
                  <button class="filter" type="button" data-filter="partial">Partial</button>
                  <button class="filter" type="button" data-filter="uncovered">Uncovered</button>
                  <button class="filter" type="button" data-filter="warning">Warnings</button>
                  <button class="filter" type="button" data-filter="error">Errors</button>
                </div>
              </div>
              <div class="report-list" id="reportList">
            """);

        foreach (var item in report.Items)
        {
            RenderItem(html, item, isRoot: true, depth: 0);
        }

        html.Append("""
              </div>
              <div class="empty-state" id="emptyState" hidden><strong>No matching entries</strong><span>Try another search or filter.</span></div>
            </section>
            </main>
            """);
        html.Append(Script);
        html.Append("</body></html>");
        return html.ToString();
    }

    private static void RenderItem(
        StringBuilder html,
        ProtoReportItem item,
        bool isRoot,
        int depth)
    {
        var statusClass = item.Status.ToString().ToLowerInvariant();
        var descendantItems = Flatten(item).ToArray();
        var coverageState = GetCoverageState(descendantItems);
        var coverageClass = coverageState switch
        {
            CoverageState.Covered => "covered",
            CoverageState.Partial => "partial",
            CoverageState.Uncovered => "uncovered",
            _ => "not-applicable"
        };
        var filterTokens = GetFilterTokens(descendantItems);
        var searchableText = string.Join(' ', descendantItems.SelectMany(entry => new[]
        {
            entry.Identifier,
            entry.TargetName,
            entry.Category,
            entry.Kind.ToString(),
            entry.Message ?? string.Empty,
            entry.Tags is null ? string.Empty : string.Join(' ', entry.Tags)
        })).ToLowerInvariant();

        var hasDetails = HasDetails(item);
        var container = hasDetails ? "details" : "article";

        html.Append('<').Append(container).Append(" class=\"report-item ").Append(coverageClass).Append(' ')
            .Append("status-").Append(statusClass).Append(isRoot ? " root" : " child")
            .Append("\" data-report-item=\"").Append(isRoot ? "root" : "child").Append('"');
        if (isRoot)
        {
            html.Append(" data-search=\"").Append(Encode(searchableText)).Append("\" data-filters=\"")
                .Append(filterTokens).Append('"');
        }
        if (hasDetails && depth < 1) html.Append(" open");
        html.Append('>');

        html.Append(hasDetails ? "<summary>" : "<div class=\"item-summary\">");
        html.Append(hasDetails
                ? "<span class=\"chevron\" aria-hidden=\"true\">›</span>"
                : "<span class=\"chevron-placeholder\" aria-hidden=\"true\"></span>")
            .Append("<span class=\"status-dot\" aria-hidden=\"true\"></span>")
            .Append("<span class=\"item-heading\"><strong");
        var displayIdentifier = GetDisplayIdentifier(item);
        if (!string.Equals(displayIdentifier, item.Identifier, StringComparison.Ordinal))
        {
            html.Append(" title=\"").Append(Encode(item.Identifier)).Append('"');
        }
        html.Append('>').Append(Encode(displayIdentifier)).Append("</strong>")
            .Append("<span class=\"item-context\">").Append(Encode(GetContextLabel(item, isRoot)))
            .Append("</span></span>")
            .Append("<span class=\"item-badges\">");

        if (coverageState != CoverageState.NotApplicable)
        {
            html.Append("<span class=\"badge coverage-badge\">")
                .Append(coverageState).Append("</span>");
        }
        if (item.Status != ProtoReportStatus.Neutral)
        {
            html.Append("<span class=\"badge status-badge\">").Append(Encode(item.Status.ToString())).Append("</span>");
        }
        if (item.Count > 0)
        {
            html.Append("<span class=\"badge\">").Append(item.Count.ToString(CultureInfo.InvariantCulture))
                .Append(" occurrence").Append(Plural(item.Count)).Append("</span>");
        }
        html.Append(hasDetails ? "</span></summary><div class=\"item-body\">" : "</span></div>");

        if (!hasDetails)
        {
            html.Append("</article>");
            return;
        }

        if (item.Value is not null)
        {
            html.Append("<div class=\"measured-value\"><strong>")
                .Append(item.Value.Value.ToString(CultureInfo.InvariantCulture)).Append("</strong><span>")
                .Append(Encode(item.Unit)).Append("</span></div>");
        }
        if (!string.IsNullOrWhiteSpace(item.Message))
        {
            html.Append("<p class=\"message\">").Append(Encode(item.Message)).Append("</p>");
        }
        if (item.Tags is { Count: > 0 })
        {
            html.Append("<div class=\"tags\">");
            foreach (var tag in item.Tags)
            {
                html.Append("<span class=\"tag\">#").Append(Encode(tag)).Append("</span>");
            }
            html.Append("</div>");
        }
        if (item.Metadata is { Count: > 0 })
        {
            html.Append("<details class=\"metadata\"><summary>Metadata</summary><pre>")
                .Append(Encode(JsonSerializer.Serialize(item.Metadata, new JsonSerializerOptions { WriteIndented = true })))
                .Append("</pre></details>");
        }
        if (item.Children is { Count: > 0 })
        {
            html.Append("<div class=\"children\">");
            foreach (var child in item.Children)
            {
                RenderItem(html, child, isRoot: false, depth + 1);
            }
            html.Append("</div>");
        }
        html.Append("</div></details>");
    }

    private static bool HasDetails(ProtoReportItem item)
        => item.Value is not null
            || !string.IsNullOrWhiteSpace(item.Message)
            || item.Tags is { Count: > 0 }
            || item.Metadata is { Count: > 0 }
            || item.Children is { Count: > 0 };

    private static string GetDisplayIdentifier(ProtoReportItem item)
    {
        if (item.Category == "OpenAPI Response")
        {
            return string.Equals(item.Identifier, "default", StringComparison.OrdinalIgnoreCase)
                ? "Default response"
                : $"{item.Identifier} response";
        }

        if (item.Category != "OpenAPI Property") return item.Identifier;

        var path = item.Identifier.Trim();
        if (path == "$") return "Response body";
        if (path.StartsWith("$.", StringComparison.Ordinal)) path = path[2..];
        path = path.Replace("[]", ".item", StringComparison.Ordinal);
        return string.Join(" › ", path.Split('.', StringSplitOptions.RemoveEmptyEntries));
    }

    private static string GetContextLabel(ProtoReportItem item, bool isRoot)
    {
        var category = item.Category switch
        {
            "OpenAPI Response" => "Response",
            "OpenAPI Property" => "Property",
            _ => item.Category
        };
        return isRoot ? $"{item.TargetName} · {category}" : category;
    }

    private static string GetFilterTokens(IEnumerable<ProtoReportItem> items)
    {
        var materializedItems = items.ToArray();
        var tokens = new HashSet<string>(StringComparer.Ordinal);
        if (GetCoverageState(materializedItems) == CoverageState.Partial)
        {
            tokens.Add("partial");
        }
        foreach (var item in materializedItems)
        {
            if (item.IsCovered is true) tokens.Add("covered");
            if (item.IsCovered is false) tokens.Add("uncovered");
            if (item.Status == ProtoReportStatus.Warning) tokens.Add("warning");
            if (item.Status == ProtoReportStatus.Error) tokens.Add("error");
        }

        return string.Join(' ', tokens);
    }

    private static CoverageState GetCoverageState(IEnumerable<ProtoReportItem> items)
    {
        var hasCovered = false;
        var hasUncovered = false;
        foreach (var item in items.Where(item => item.Kind == ProtoReportItemKind.Coverage))
        {
            hasCovered |= item.IsCovered is true;
            hasUncovered |= item.IsCovered is false;
        }

        if (hasCovered && hasUncovered) return CoverageState.Partial;
        if (hasCovered) return CoverageState.Covered;
        if (hasUncovered) return CoverageState.Uncovered;
        return CoverageState.NotApplicable;
    }

    private static IEnumerable<ProtoReportItem> Flatten(ProtoReportItem item)
    {
        yield return item;
        if (item.Children is null) yield break;
        foreach (var child in item.Children)
        {
            foreach (var descendant in Flatten(child)) yield return descendant;
        }
    }

    private static void SummaryCard(
        StringBuilder html,
        string label,
        int value,
        string description,
        string tone)
    {
        html.Append("<article class=\"metric ").Append(tone).Append("\"><span>").Append(Encode(label))
            .Append("</span><strong>").Append(value.ToString(CultureInfo.InvariantCulture))
            .Append("</strong><small>").Append(Encode(description)).Append("</small></article>");
    }

    private static string Plural(int count) => count == 1 ? string.Empty : "s";

    private static string Encode(string? value) => WebUtility.HtmlEncode(value ?? string.Empty);

    private enum CoverageState
    {
        NotApplicable,
        Covered,
        Partial,
        Uncovered
    }

    private const string Styles = """
        <style>
        :root{--bg:#09090b;--surface:#111113;--surface-2:#18181b;--hover:#1f1f23;--border:#29292e;--text:#f4f4f5;--muted:#a1a1aa;--dim:#71717a;--accent:#9b8afb;--accent-soft:#9b8afb1d;--success:#5cdb95;--success-soft:#5cdb9517;--warning:#f4bf50;--warning-soft:#f4bf501a;--danger:#fb7185;--danger-soft:#fb718519;color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
        :root[data-theme="light"]{--bg:#f7f7f8;--surface:#fff;--surface-2:#f4f4f5;--hover:#eeeef0;--border:#e4e4e7;--border-strong:#d4d4d8;--text:#18181b;--muted:#52525b;--dim:#a1a1aa;--accent:#6754d9;--accent-soft:#6754d913;--success:#16804b;--success-soft:#16804b12;--warning:#a16207;--warning-soft:#a1620714;--danger:#d9344b;--danger-soft:#d9344b12;color-scheme:light}
        *{box-sizing:border-box}html,body{margin:0;min-height:100%}body{background:var(--bg);color:var(--text);font-size:14px;line-height:1.5;-webkit-font-smoothing:antialiased}.topbar{position:sticky;top:0;z-index:20;height:64px;padding:0 24px;display:grid;grid-template-columns:minmax(180px,1fr) auto minmax(180px,1fr);align-items:center;gap:20px;background:color-mix(in srgb,var(--surface) 92%,transparent);border-bottom:1px solid var(--border);backdrop-filter:blur(14px)}.brand{display:flex;align-items:center;gap:10px}.brand-mark{width:36px;height:36px;display:block}.brand-mark svg{width:36px;height:36px;display:block;overflow:visible}.brand span:last-child{display:flex;flex-direction:column;line-height:1.15}.brand strong{font-size:14px}.brand small,.eyebrow{font-size:9px;letter-spacing:.13em;color:var(--dim)}.run-state{justify-self:center}.state-pill{display:inline-flex;align-items:center;gap:8px;padding:5px 11px;border:1px solid var(--border);border-radius:999px;font-size:12px;font-weight:600;background:var(--surface-2)}.state-pill i,.status-dot{width:7px;height:7px;border-radius:50%;background:var(--success);box-shadow:0 0 0 3px var(--success-soft)}.state-pill.attention i{background:var(--danger);box-shadow:0 0 0 3px var(--danger-soft)}.top-actions{justify-self:end;display:flex;align-items:center;gap:8px}.search{height:34px;width:260px;display:flex;align-items:center;gap:8px;padding:0 9px;border:1px solid var(--border);border-radius:8px;background:var(--surface-2);color:var(--dim)}.search:focus-within{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-soft);background:var(--surface)}.search input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:var(--text);font:inherit;font-size:12px}.search kbd{padding:0 5px;border:1px solid var(--border);border-radius:4px;background:var(--surface);font-size:10px}.icon-button{width:34px;height:34px;border:1px solid var(--border);border-radius:8px;background:var(--surface-2);color:var(--muted);cursor:pointer;font-size:16px}.icon-button:hover{background:var(--hover);color:var(--text)}main{width:min(1240px,calc(100% - 40px));margin:0 auto 64px}.hero{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:42px 4px 24px}.hero h1{margin:3px 0 4px;font-size:28px;letter-spacing:-.035em}.generated{margin:0;color:var(--muted);font-size:12px}.coverage-ring{--coverage:0;width:88px;height:88px;position:relative;display:grid;place-items:center;border-radius:50%;background:conic-gradient(var(--accent) calc(var(--coverage)*1%),var(--surface-2) 0)}.coverage-ring:before{content:"";position:absolute;inset:7px;border-radius:inherit;background:var(--bg)}.coverage-ring span,.coverage-ring em{position:relative;z-index:1}.coverage-ring span{font-weight:750;font-size:20px;line-height:1;margin-top:-8px}.coverage-ring small{font-size:11px;color:var(--muted)}.coverage-ring em{position:absolute;top:52px;font-size:9px;color:var(--dim);font-style:normal;text-transform:uppercase;letter-spacing:.08em}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-bottom:18px}.metric{position:relative;min-width:0;padding:14px 16px;border:1px solid var(--border);border-radius:10px;background:var(--surface);overflow:hidden}.metric:before{content:"";position:absolute;inset:0 auto 0 0;width:3px;background:var(--dim)}.metric.accent:before{background:var(--accent)}.metric.success:before{background:var(--success)}.metric.warning:before{background:var(--warning)}.metric.danger:before{background:var(--danger)}.metric>span{display:block;color:var(--muted);font-size:11px}.metric>strong{display:block;margin:2px 0;font-size:23px;letter-spacing:-.03em}.metric>small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dim);font-size:10px}.report-panel{border:1px solid var(--border);border-radius:12px;background:var(--surface);overflow:hidden;box-shadow:0 8px 30px #0000000d}.panel-toolbar{min-height:62px;padding:12px 16px;display:flex;align-items:center;justify-content:space-between;gap:16px;border-bottom:1px solid var(--border)}.panel-toolbar h2{display:inline;margin:0 8px 0 0;font-size:14px}.panel-toolbar #resultCount{color:var(--dim);font-size:11px}.filters{display:flex;gap:3px;padding:3px;border:1px solid var(--border);border-radius:8px;background:var(--surface-2)}.filter{border:0;border-radius:6px;padding:5px 10px;background:transparent;color:var(--muted);font:inherit;font-size:11px;cursor:pointer}.filter:hover{color:var(--text)}.filter.active{background:var(--surface);color:var(--text);box-shadow:0 1px 4px #0002}.report-list{padding:10px}.report-item{border:1px solid var(--border);border-radius:9px;background:var(--surface);overflow:hidden}.report-item.root+.report-item.root{margin-top:7px}.report-item.child{margin-top:6px;background:var(--surface-2)}.report-item[hidden]{display:none}.report-item>summary,.report-item>.item-summary{list-style:none;min-height:54px;padding:10px 12px;display:flex;align-items:center;gap:10px;transition:background .12s}.report-item>summary{cursor:pointer}.report-item>summary::-webkit-details-marker{display:none}.report-item>summary:hover{background:var(--hover)}.chevron,.chevron-placeholder{width:11px;flex:0 0 11px}.chevron{color:var(--dim);font-size:19px;transition:transform .15s}.report-item[open]>summary .chevron{transform:rotate(90deg)}.status-dot{flex:0 0 auto}.uncovered>summary .status-dot,.uncovered>.item-summary .status-dot,.status-error>summary .status-dot,.status-error>.item-summary .status-dot{background:var(--danger);box-shadow:0 0 0 3px var(--danger-soft)}.status-warning>summary .status-dot,.status-warning>.item-summary .status-dot{background:var(--warning);box-shadow:0 0 0 3px var(--warning-soft)}.not-applicable.status-neutral>summary .status-dot,.not-applicable.status-neutral>.item-summary .status-dot{background:var(--dim);box-shadow:none}.item-heading{display:flex;min-width:0;flex:1;flex-direction:column}.item-heading strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.item-context{color:var(--dim);font-size:10px}.item-badges{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:5px}.badge,.tag{display:inline-flex;align-items:center;padding:2px 7px;border:1px solid var(--border);border-radius:999px;color:var(--muted);font-size:9px;white-space:nowrap}.covered>summary .coverage-badge,.covered>.item-summary .coverage-badge{border-color:color-mix(in srgb,var(--success) 35%,var(--border));color:var(--success);background:var(--success-soft)}.uncovered>summary .coverage-badge,.uncovered>.item-summary .coverage-badge{border-color:color-mix(in srgb,var(--danger) 35%,var(--border));color:var(--danger);background:var(--danger-soft)}.status-warning>summary .status-badge,.status-warning>.item-summary .status-badge{color:var(--warning);background:var(--warning-soft)}.status-error>summary .status-badge,.status-error>.item-summary .status-badge{color:var(--danger);background:var(--danger-soft)}.item-body{padding:0 12px 12px 41px;border-top:1px solid var(--border)}.report-item:not([open])>.item-body{display:none}.message{margin:12px 0 0;padding:9px 11px;border-left:3px solid var(--accent);border-radius:0 6px 6px 0;background:var(--accent-soft);white-space:pre-wrap}.measured-value{display:flex;align-items:baseline;gap:7px;margin-top:12px}.measured-value strong{font-size:24px}.measured-value span{color:var(--muted)}.tags{display:flex;gap:5px;margin-top:10px}.tag{color:var(--accent);border-color:color-mix(in srgb,var(--accent) 30%,var(--border));background:var(--accent-soft)}.metadata{margin-top:10px}.metadata>summary{width:max-content;color:var(--muted);font-size:11px;cursor:pointer}.metadata pre{max-height:320px;overflow:auto;margin:8px 0 0;padding:12px;border:1px solid var(--border);border-radius:7px;background:var(--bg);color:var(--muted);font:11px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.children{margin-top:10px;padding-left:12px;border-left:1px solid var(--border)}.empty-state{padding:70px 20px;text-align:center}.empty-state strong,.empty-state span{display:block}.empty-state span{margin-top:4px;color:var(--dim);font-size:12px}
        .partial>summary .status-dot,.partial>.item-summary .status-dot{background:var(--warning);box-shadow:0 0 0 3px var(--warning-soft)}.partial>summary .coverage-badge,.partial>.item-summary .coverage-badge{border-color:color-mix(in srgb,var(--warning) 35%,var(--border));color:var(--warning);background:var(--warning-soft)}
        :root{--bg:#0b1115;--surface:#111a20;--surface-2:#17232b;--hover:#1b2b34;--border:#263943;--border-strong:#385461;--text:#ecf4f7;--muted:#a2b4bd;--dim:#718892;--blueprint:#4eb7ee;--blueprint-soft:#4eb7ee18;--accent:var(--blueprint);--accent-soft:var(--blueprint-soft);--success:#5cdb95;--success-soft:#5cdb9517;--warning:#f0bd55;--warning-soft:#f0bd5519;--danger:#fb7185;--danger-soft:#fb718519;--shadow:#00000035}
        :root[data-theme="light"]{--bg:#f6f7f8;--surface:#fff;--surface-2:#f1f5f7;--hover:#eaf4f8;--border:#d8e2e7;--border-strong:#b8ccd6;--text:#102a3b;--muted:#587080;--dim:#8aa0ad;--blueprint:#087fc4;--blueprint-soft:#087fc414;--accent:var(--blueprint);--accent-soft:var(--blueprint-soft);--success:#16835a;--success-soft:#16835a14;--warning:#a66b08;--warning-soft:#a66b0817;--danger:#d74355;--danger-soft:#d7435514;--shadow:#13394d12}
        *{scrollbar-width:thin;scrollbar-color:var(--border-strong) transparent}*::-webkit-scrollbar{width:10px;height:10px}*::-webkit-scrollbar-track{background:transparent}*::-webkit-scrollbar-thumb{min-height:36px;border:2px solid transparent;border-radius:999px;background:var(--border-strong);background-clip:padding-box}*::-webkit-scrollbar-thumb:hover{background-color:var(--blueprint)}*::-webkit-scrollbar-corner{background:transparent}
        body{background-color:var(--bg);background-image:linear-gradient(#168ac108 1px,transparent 1px),linear-gradient(90deg,#168ac108 1px,transparent 1px);background-size:28px 28px}.brand strong{letter-spacing:.02em}.brand small,.eyebrow{text-transform:uppercase}.icon-button{border-color:var(--border-strong)}.generated{font:11px ui-monospace,Consolas,monospace}.coverage-ring,.metric,.report-panel{box-shadow:0 8px 28px var(--shadow)}.metric>strong{font-family:ui-monospace,Consolas,monospace}
        @media(max-width:1000px){.metrics{grid-template-columns:repeat(3,1fr)}.topbar{grid-template-columns:auto 1fr auto}.run-state{display:none}}@media(max-width:720px){.topbar{padding:0 12px}.search{width:min(45vw,220px)}main{width:min(100% - 20px,1240px)}.hero{padding-top:26px}.metrics{grid-template-columns:repeat(2,1fr)}.panel-toolbar{align-items:flex-start;flex-direction:column}.filters{max-width:100%;overflow:auto}.item-badges .badge:not(.coverage-badge):not(.status-badge){display:none}.item-body{padding-left:20px}.children{padding-left:7px}}@media(max-width:440px){.brand span:last-child{display:none}.search kbd{display:none}.hero h1{font-size:23px}.coverage-ring{width:74px;height:74px}.coverage-ring em{top:45px}.metrics{grid-template-columns:repeat(2,1fr)}.metric{padding:11px}.item-context{display:none}}
        </style>
        """;

    private static string ReadEmbeddedText(string resourceName)
    {
        using var stream = typeof(HtmlReportSink).Assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded reporting asset '{resourceName}' was not found.");
        using var reader = new StreamReader(stream, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private const string Script = """
        <script>
        (() => {
          const root = document.documentElement;
          const search = document.getElementById('reportSearch');
          const entries = [...document.querySelectorAll('[data-report-item="root"]')];
          const filters = [...document.querySelectorAll('[data-filter]')];
          const count = document.getElementById('resultCount');
          const empty = document.getElementById('emptyState');
          let activeFilter = 'all';

          let savedTheme;
          try { savedTheme = localStorage.getItem('prototest-report-theme'); } catch { }
          root.dataset.theme = savedTheme || (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark');
          document.getElementById('themeToggle').addEventListener('click', () => {
            root.dataset.theme = root.dataset.theme === 'dark' ? 'light' : 'dark';
            try { localStorage.setItem('prototest-report-theme', root.dataset.theme); } catch { }
          });

          function applyFilters() {
            const query = search.value.trim().toLocaleLowerCase();
            let visible = 0;
            for (const entry of entries) {
              const matchesText = !query || entry.dataset.search.includes(query);
              const matchesFilter = activeFilter === 'all' || entry.dataset.filters.split(' ').includes(activeFilter);
              entry.hidden = !(matchesText && matchesFilter);
              if (!entry.hidden) visible++;
            }
            count.textContent = `${visible} of ${entries.length} groups`;
            empty.hidden = visible !== 0;
          }

          search.addEventListener('input', applyFilters);
          for (const filter of filters) {
            filter.addEventListener('click', () => {
              activeFilter = filter.dataset.filter;
              for (const button of filters) button.classList.toggle('active', button === filter);
              applyFilters();
            });
          }
          document.addEventListener('keydown', event => {
            if (event.key === '/' && document.activeElement !== search) {
              event.preventDefault();
              search.focus();
            }
            if (event.key === 'Escape' && document.activeElement === search) {
              search.value = '';
              search.blur();
              applyFilters();
            }
          });
          applyFilters();
        })();
        </script>
        """;
}
