namespace ProtoTest.Reporting;

using ProtoTest.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

public sealed class JsonReportSink : IProtoSink, IProtoSinkArtifactSource, IProtoConfigurableOptions
{
    private readonly JsonReportSinkOptions _options;
    private string? _lastOutputPath;

    public JsonReportSink() : this(new JsonReportSinkOptions()) { }

    public JsonReportSink(JsonReportSinkOptions options)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
    }

    string IProtoConfigurableOptions.ConfigurationSectionName => JsonReportSinkOptions.ConfigurationSectionName;

    public string OutputPath
    {
        get => _options.OutputPath;
        set => _options.OutputPath = value;
    }

    public bool Indented
    {
        get => _options.Indented;
        set => _options.Indented = value;
    }

    public async Task ExportAsync(
        IEnumerable<ProtoReportItem> items,
        CancellationToken cancellationToken = default)
    {
        var report = ProtoReport.Create(items);
        var outputPath = Path.GetFullPath(_options.OutputPath);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

        var serializerOptions = new JsonSerializerOptions { WriteIndented = _options.Indented };
        serializerOptions.Converters.Add(new JsonStringEnumConverter());

        await using var stream = File.Create(outputPath);
        await JsonSerializer.SerializeAsync(stream, report, serializerOptions, cancellationToken);
        _lastOutputPath = outputPath;
    }

    public IReadOnlyCollection<ProtoTestAttachment> GetArtifacts()
        => _lastOutputPath is null || !File.Exists(_lastOutputPath)
            ? []
            : [ProtoTestAttachment.FromFile(_lastOutputPath, mediaType: "application/json", description: "JSON report generated by ProtoTest.Reporting")];
}
