syntax = "proto3";

package prototest.echo;

import "google/protobuf/any.proto";

option csharp_namespace = "ProtoTest.Grpc.Tests.Echo";

service Echo {
  rpc Say (EchoRequest) returns (EchoReply);
  rpc Stream (EchoRequest) returns (stream EchoReply);
  rpc Collect (stream EchoRequest) returns (EchoReply);
  rpc Chat (stream EchoRequest) returns (stream EchoReply);
}

message EchoRequest {
  string message = 1;
  string password = 2;
  google.protobuf.Any payload = 3;
}

message EchoReply {
  string message = 1;
  string password = 2;
}
