namespace ProtoTest.Core;

using Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Encapsulates the execution context and service scope for an individual test.
/// </summary>
public sealed record ProtoExecutionContext(string TestName, IServiceScope Scope, string TestId) : IAsyncDisposable
{
    private readonly IServiceScope _scope = Scope ?? throw new ArgumentNullException(nameof(Scope));
    private readonly Dictionary<Type, IProtoContext> _contexts = [];

    public string TestName { get; } = TestName ?? throw new ArgumentNullException(nameof(TestName));
    /// <summary>
    /// Deterministic 5-digit numeric test ID scoped across assembly boundaries, generated by <see cref="ProtoTestIdGenerator"/>.
    /// </summary>
    public string TestId { get; } = TestId ?? throw new ArgumentNullException(nameof(TestId));
    public IServiceProvider Services => _scope.ServiceProvider;

    /// <summary>
    /// Registers or overrides a contextual state instance for the current test execution.
    /// </summary>
    /// <typeparam name="T">The context type implementing <see cref="IProtoContext"/>.</typeparam>
    /// <param name="context">The contextual state instance to associate.</param>
    public void Set<T>(T context) where T : class, IProtoContext
    {
        ArgumentNullException.ThrowIfNull(context);
        _contexts[typeof(T)] = context;
    }

    /// <summary>
    /// Retrieves a registered context instance if present.
    /// </summary>
    /// <typeparam name="T">The context type implementing <see cref="IProtoContext"/>.</typeparam>
    /// <returns>The registered instance, or <c>null</c> if not found.</returns>
    public T? Get<T>() where T : class, IProtoContext
    {
        return _contexts.TryGetValue(typeof(T), out var ctx) ? (T)ctx : null;
    }

    /// <summary>
    /// Retrieves a required context instance, throwing an exception if it has not been registered.
    /// </summary>
    /// <typeparam name="T">The context type implementing <see cref="IProtoContext"/>.</typeparam>
    /// <returns>The registered context instance.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the requested context type is missing.</exception>
    public T GetRequired<T>() where T : class, IProtoContext
    {
        return Get<T>()
            ?? throw new InvalidOperationException($"No context of type '{typeof(T).Name}' registered.");
    }

    /// <summary>
    /// Disposes the underlying service scope asynchronously.
    /// </summary>
    public ValueTask DisposeAsync()
    {
        if (_scope is IAsyncDisposable asyncDisposable)
        {
            return asyncDisposable.DisposeAsync();
        }

        _scope.Dispose();
        return ValueTask.CompletedTask;
    }
}