<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.70.0" />
    <PackageReference Include="Grpc.Tools" Version="2.70.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\ProtoTest.Core\ProtoTest.Core.csproj" />
    <ProjectReference Include="..\..\src\ProtoTest.Grpc\ProtoTest.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\echo.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>

