import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The Learn track is its own docs instance with its own sidebar: lessons read top to bottom without the
 * reference tree beside them. Section order and labels live in each folder's _category_.json, like the
 * reference sidebar.
 */
const sidebars: SidebarsConfig = {
  learnSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
