<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ProtoTest.Core\ProtoTest.Core.csproj" />
    <ProjectReference Include="..\..\src\ProtoTest.Sheets\ProtoTest.Sheets.csproj" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ProtoTest.TestSupport\ProtoTest.TestSupport.csproj" />
  </ItemGroup>
</Project>
